import type { Rarity } from '../data/collections';
interface ArtProps{id:string;name:string;rarity:Rarity;color:string;size?:number;animated?:boolean}
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0}
const hi=(r:Rarity)=>['legendary','mythic','secret'].includes(r);
function effect(n:string){const x=n.toLowerCase();if(x.includes('flame')||x.includes('ember')||x.includes('inferno')||x.includes('solar'))return'flame';if(x.includes('frost')||x.includes('ice'))return'ice';if(x.includes('storm')||x.includes('ragnarok')||x.includes('thunder'))return'bolt';if(x.includes('cosmic')||x.includes('galaxy')||x.includes('celestial'))return'star';if(x.includes('void')||x.includes('abyss')||x.includes('dimensional'))return'void';if(x.includes('shadow')||x.includes('phantom')||x.includes('eclipse'))return'shadow';if(x.includes('dragon'))return'dragon';if(x.includes('blood')||x.includes('crimson'))return'blood';return'orb'}
export function AuraArt({id,name,rarity,color,size=120,animated=true}:ArtProps){const e=effect(name),h=hash(id+name),u=`pa-${id.replace(/[^a-z0-9]/gi,'')}`,high=hi(rarity),count=10+(h%9),rotation=(h%360);return <svg viewBox="0 0 120 120" width={size} height={size} className="overflow-visible"><defs><radialGradient id={`${u}g`}><stop stopColor="#fff" stopOpacity=".98"/><stop offset=".24" stopColor={color} stopOpacity=".96"/><stop offset="1" stopColor={color} stopOpacity="0"/></radialGradient><filter id={`${u}b`}><feGaussianBlur stdDeviation={3+(h%3)}/></filter></defs><circle cx="60" cy="60" r={53+(h%4)} fill={`url(#${u}g)`} opacity=".42" filter={`url(#${u}b)`}/><circle cx="60" cy="60" r={39+(h%6)} fill="none" stroke={color} strokeOpacity=".22" strokeWidth="1" strokeDasharray={`${1+(h%4)} ${4+(h%5)}`} style={{transformOrigin:'60px 60px',animation:animated?'aura-rotate 8s linear infinite':'none',transform:`rotate(${rotation}deg)`}}/>{high&&<circle cx="60" cy="60" r="47" fill="none" stroke={color} strokeOpacity=".28" strokeWidth="1.5" strokeDasharray="2 6"/>}<circle cx="60" cy="60" r={22+(h%6)} fill="none" stroke={color} strokeOpacity=".32" strokeWidth="2"/>{e==='flame'&&<Flame c={color} h={h} count={count}/>} {e==='ice'&&<Ice c={color} h={h} count={count}/>} {e==='bolt'&&<Bolt c={color} h={h} count={count}/>} {e==='star'&&<Star c={color} h={h} count={count}/>} {e==='void'&&<Void c={color} h={h}/>} {e==='shadow'&&<Shadow c={color} h={h}/>} {e==='dragon'&&<Dragon c={color} h={h}/>} {e==='blood'&&<Blood c={color} h={h}/>} {e==='orb'&&<Orb c={color} h={h}/>}<circle cx="60" cy="60" r={12+(h%5)} fill={`url(#${u}g)`} className={animated?'aura-pulse-core':''}/><circle cx="60" cy="60" r="4.5" fill="#fff" opacity=".88"/><style>{`.aura-pulse-core{animation:pac 2s ease-in-out infinite;transform-origin:60px 60px}.aura-rotate{animation:par 8s linear infinite}@keyframes pac{50%{transform:scale(1.2);opacity:.72}}@keyframes par{to{transform:rotate(360deg)}}`}</style></svg>}
function Flame({c,h,count}:{c:string;h:number;count:number}){return <g>{Array.from({length:count},(_,i)=>{const a=i*Math.PI*2/count,r=28+(h+i*7)%13,x=60+Math.cos(a)*r,y=60+Math.sin(a)*r,s=7+(h+i)%8;return <path key={i} d={`M${x} ${y}q-${s/2}-${s} 0-${s*2}q${s} ${s} 0 ${s*2}Z`} fill={c} opacity={.55+((i+h)%4)/10}/>)}</g>}
function Ice({c,h,count}:{c:string;h:number;count:number}){return <g>{Array.from({length:count},(_,i)=>{const a=i*Math.PI*2/count,r=31+(h+i)%9;return <path key={i} d={`M60 60L${60+Math.cos(a)*r} ${60+Math.sin(a)*r}`} stroke={c} strokeWidth={1.5+(i%3)*.5} opacity=".75"/>})}</g>}
function Bolt({c,h,count}:{c:string;h:number;count:number}){return <g>{Array.from({length:Math.min(count,12)},(_,i)=>{const a=i*Math.PI*2/count,r=43+(h%5),x=60+Math.cos(a)*r,y=60+Math.sin(a)*r;return <path key={i} d={`M60 60L${60+Math.cos(a)*24} ${60+Math.sin(a)*24}L${x} ${y}`} fill="none" stroke={c} strokeWidth={1.5+(i%2)} strokeLinecap="round"/>)}</g>}
function Star({c,h,count}:{c:string;h:number;count:number}){return <g>{Array.from({length:count+4},(_,i)=>{const a=i*Math.PI*2/(count+4),r=31+(h+i*3)%17;return <circle key={i} cx={60+Math.cos(a)*r} cy={60+Math.sin(a)*r} r={i%4===0?2:1} fill={c}/>)}</g>}
function Void({c,h}:{c:string;h:number}){return <g>{[18,25,32,39,46].map((r,i)=><circle key={r} cx="60" cy="60" r={r+(h%3)} fill="none" stroke={c} strokeOpacity={.18+i*.12} strokeWidth={1.3+(i%2)} strokeDasharray={`${4+(h%5)+i*2} ${3+(i%4)}`}/>)}</g>}
function Shadow({c,h}:{c:string;h:number}){return <g><path d="M60 16C35 23 20 45 27 65c5 17 20 27 33 40 13-13 28-23 33-40 7-20-8-42-33-49Z" fill={c} opacity=".28" stroke={c} strokeWidth="2"/><path d="M60 24Q43 43 60 58Q77 43 60 24Z" fill="#000" opacity={.2+(h%3)/10}/></g>}
function Dragon({c,h}:{c:string;h:number}){return <g fill="none" stroke={c} strokeWidth={1.8+(h%2)} opacity=".82"><path d="M22 72Q38 27 60 48Q82 27 98 72Q78 57 60 80Q42 57 22 72Z"/><path d="M39 51L31 35M81 51L89 35M48 63L39 78M72 63L81 78"/></g>}
function Blood({c,h}:{c:string;h:number}){return <g>{[26,34,42].map((r,i)=><circle key={r} cx="60" cy="60" r={r} fill="none" stroke={c} strokeWidth={2-i*.4} strokeOpacity={.45+i*.12} strokeDasharray={`${8+(h%5)} ${4+i*2}`}/>)}</g>}
function Orb({c,h}:{c:string;h:number}){return <g fill="none" stroke={c} opacity=".65"><circle cx="60" cy="60" r={30+(h%5)}/><ellipse cx="60" cy="60" rx={40+(h%4)} ry="17" transform={`rotate(${h%180} 60 60)`}/><ellipse cx="60" cy="60" rx="17" ry="40" transform={`rotate(${(h+55)%180} 60 60)`}/></g>}
