import type { Rarity } from '../data/collections';
interface ArtProps{id:string;name:string;rarity:Rarity;color:string;size?:number;animated?:boolean}
const hi=(r:Rarity)=>['legendary','mythic','secret'].includes(r);
function effect(n:string){const x=n.toLowerCase();if(x.includes('flame')||x.includes('ember')||x.includes('inferno'))return'flame';if(x.includes('frost')||x.includes('ice'))return'ice';if(x.includes('storm')||x.includes('ragnarok'))return'bolt';if(x.includes('cosmic')||x.includes('galaxy'))return'star';if(x.includes('void')||x.includes('abyss'))return'void';if(x.includes('shadow')||x.includes('phantom'))return'shadow';if(x.includes('dragon'))return'dragon';return'orb'}
export function AuraArt({id,name,rarity,color,size=120,animated=true}:ArtProps){const e=effect(name),u=`pa-${id.replace(/[^a-z0-9]/gi,'')}`,h=hi(rarity);return <svg viewBox="0 0 120 120" width={size} height={size} className="overflow-visible"><defs><radialGradient id={`${u}g`}><stop stopColor="#fff" stopOpacity=".95"/><stop offset=".25" stopColor={color} stopOpacity=".95"/><stop offset="1" stopColor={color} stopOpacity="0"/></radialGradient><filter id={`${u}b`}><feGaussianBlur stdDeviation="4"/></filter></defs><circle cx="60" cy="60" r="54" fill={`url(#${u}g)`} opacity=".38" filter={`url(#${u}b)`}/>{h&&<circle cx="60" cy="60" r="43" fill="none" stroke={color} strokeOpacity=".45" strokeWidth="1" strokeDasharray="1 5" className={animated?'aura-rotate':''}/>}<circle cx="60" cy="60" r="25" fill="none" stroke={color} strokeOpacity=".35" strokeWidth="2"/>{e==='flame'&&<Flame c={color} u={u}/>} {e==='ice'&&<Ice c={color}/>} {e==='bolt'&&<Bolt c={color}/>} {e==='star'&&<Star c={color}/>} {e==='void'&&<Void c={color}/>} {e==='shadow'&&<Shadow c={color}/>} {e==='dragon'&&<Dragon c={color}/>} {e==='orb'&&<Orb c={color}/>}<circle cx="60" cy="60" r="14" fill={`url(#${u}g)`} className={animated?'aura-pulse-core':''}/><circle cx="60" cy="60" r="5" fill="#fff" opacity=".85"/><style>{`.aura-pulse-core{animation:pac 2s ease-in-out infinite;transform-origin:60px 60px}.aura-rotate{animation:par 8s linear infinite;transform-origin:60px 60px}@keyframes pac{50%{transform:scale(1.18);opacity:.7}}@keyframes par{to{transform:rotate(360deg)}}`}</style></svg>}
function Flame({c,u}:{c:string;u:string}){return <g>{Array.from({length:12},(_,i)=>{const a=i*Math.PI*2/12,r=30+(i%3)*4,x=60+Math.cos(a)*r,y=60+Math.sin(a)*r;return <path key={i} d={`M${x} ${y}q-7-10 0-18q7 10 0 18Z`} fill={c} opacity=".8"/>})}</g>}
function Ice({c}:{c:string}){return <g>{Array.from({length:10},(_,i)=>{const a=i*Math.PI*2/10,r=34;return <path key={i} d={`M60 ${60}L${60+Math.cos(a)*r} ${60+Math.sin(a)*r}`} stroke={c} strokeWidth="2" opacity=".75"/>})}</g>}
function Bolt({c}:{c:string}){return <g>{Array.from({length:8},(_,i)=>{const a=i*Math.PI/4;const x=60+Math.cos(a)*44,y=60+Math.sin(a)*44;return <path key={i} d={`M60 60L${60+Math.cos(a)*25} ${60+Math.sin(a)*25}L${x} ${y}`} fill="none" stroke={c} strokeWidth="2" strokeLinecap="round"/>})}</g>}
function Star({c}:{c:string}){return <g>{Array.from({length:14},(_,i)=>{const a=i*Math.PI*2/14,r=36+(i%2)*8;return <circle key={i} cx={60+Math.cos(a)*r} cy={60+Math.sin(a)*r} r={i%3===0?2:1} fill={c}/>)}</g>}
function Void({c}:{c:string}){return <g>{[20,27,34,41].map((r,i)=><circle key={r} cx="60" cy="60" r={r} fill="none" stroke={c} strokeOpacity={.2+i*.12} strokeWidth="2" strokeDasharray={`${5+i*3} ${3+i*2}`}/>)}</g>}
function Shadow({c}:{c:string}){return <path d="M60 18C35 24 22 44 28 62c5 17 19 28 32 39 13-11 27-22 32-39 6-18-7-38-32-44Z" fill={c} opacity=".32" stroke={c} strokeWidth="2"/>}
function Dragon({c}:{c:string}){return <g fill="none" stroke={c} strokeWidth="2" opacity=".8"><path d="M24 70Q40 30 60 48Q80 30 96 70Q78 58 60 78Q42 58 24 70Z"/><path d="M40 52L34 38M80 52L86 38"/></g>}
function Orb({c}:{c:string}){return <g fill="none" stroke={c} opacity=".65"><circle cx="60" cy="60" r="34"/><circle cx="60" cy="60" r="40" strokeDasharray="2 5"/></g>}
