import { motion, AnimatePresence } from 'framer-motion';
import { Download, X, CheckCircle2, Smartphone, Sparkles } from 'lucide-react';
import { useState, useEffect, useCallback, type ReactNode } from 'react';
const DISMISS_KEY='pwa-install-dismissed'; const DISMISS_COOLDOWN_MS=3*24*60*60*1000;
interface InstallButtonProps{isInstallable:boolean;isInstalled:boolean;onInstall:()=>Promise<boolean>;children?:ReactNode;}
export function InstallButton({isInstallable,isInstalled,onInstall,children}:InstallButtonProps){
 const[showModal,setShowModal]=useState(false),[showInstructions,setShowInstructions]=useState(false),[installing,setInstalling]=useState(false),[showSuccess,setShowSuccess]=useState(false),[sessionDismissed,setSessionDismissed]=useState(false);
 const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!(window as any).MSStream;
 const shouldShowPrompt=useCallback(()=>{if(isInstalled||sessionDismissed)return false;const d=localStorage.getItem(DISMISS_KEY);return !(d&&Date.now()-parseInt(d,10)<DISMISS_COOLDOWN_MS)},[isInstalled,sessionDismissed]);
 useEffect(()=>{if(!shouldShowPrompt())return;if(isInstallable||(isIOS&&!isInstalled)){const t=setTimeout(()=>setShowModal(true),2500);return()=>clearTimeout(t)}},[isInstallable,isIOS,isInstalled,shouldShowPrompt]);
 const handleDismiss=useCallback(()=>{setShowModal(false);setSessionDismissed(true);localStorage.setItem(DISMISS_KEY,Date.now().toString())},[]);
 const handleInstall=async()=>{if(installing)return;setInstalling(true);const success=await onInstall();setInstalling(false);if(success){setShowSuccess(true);setShowModal(false);localStorage.removeItem(DISMISS_KEY);setTimeout(()=>setShowSuccess(false),4000)}else{setShowModal(false);setShowInstructions(true)}};
 const closeInstructions=useCallback(()=>{setShowInstructions(false);setSessionDismissed(true);localStorage.setItem(DISMISS_KEY,Date.now().toString())},[]);
 const showIOSInstructions=isIOS&&!isInstalled&&!isInstallable;
 return <>
  {children&&<button type="button" onClick={()=>void handleInstall()} disabled={isInstalled||installing} className="btn-ghost border border-white/10 px-3 py-2 whitespace-nowrap"><Download size={16}/><span>{isInstalled?'Installed':installing?'Installing…':children}</span></button>}
  <AnimatePresence>{showModal&&!isInstalled&&shouldShowPrompt()&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[100] flex items-center justify-center p-3 sm:p-4 overflow-y-auto"><div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={handleDismiss}/><motion.div initial={{scale:.96,opacity:0,y:12}} animate={{scale:1,opacity:1,y:0}} exit={{scale:.96,opacity:0,y:12}} className="relative card-premium p-4 sm:p-6 max-w-sm w-full max-h-[calc(100dvh-1.5rem)] overflow-y-auto"><button onClick={handleDismiss} className="absolute top-3 right-3 p-1.5 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-white/5"><X size={18}/></button><div className="text-center mb-4 sm:mb-5 pr-5"><div className="w-14 h-14 sm:w-16 sm:h-16 rounded-2xl flex items-center justify-center mx-auto mb-3 sm:mb-4" style={{background:'linear-gradient(135deg,rgba(255,122,24,.2),rgba(232,93,0,.05))'}}><Sparkles size={26} className="text-ember-400"/></div><h3 className="font-display font-bold text-lg mb-1">Install STRYVEN</h3><p className="text-sm text-slate-400 leading-5">Add STRYVEN to your device for quick access and offline support.</p></div><div className="space-y-2 mb-4 sm:mb-5">{['Instant home-screen access','Works offline','Full-screen experience'].map((x,i)=><div key={i} className="flex items-center gap-3 px-3 py-2 rounded-lg bg-white/5"><span>{['⚡','📱','🎮'][i]}</span><span className="text-xs text-slate-300">{x}</span></div>)}</div><div className="flex gap-2"><button onClick={handleDismiss} className="flex-1 py-3 rounded-xl text-sm font-semibold text-slate-300 bg-white/5">Not Now</button><button onClick={()=>void handleInstall()} disabled={installing} className="flex-1 py-3 rounded-xl text-sm font-semibold text-white bg-gradient-to-r from-ember-500 to-orange-600 disabled:opacity-60">{installing?'Installing…':'Install'}</button></div></motion.div></motion.div>}</AnimatePresence>
  <AnimatePresence>{(showIOSInstructions||showInstructions)&&!isInstalled&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[100] flex items-center justify-center p-3 sm:p-4 overflow-y-auto"><div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={closeInstructions}/><div className="relative card-premium p-5 sm:p-6 max-w-sm w-full max-h-[calc(100dvh-1.5rem)] overflow-y-auto"><button onClick={closeInstructions} className="absolute top-3 right-3 p-1.5 text-slate-400"><X size={18}/></button><div className="flex items-center gap-3 mb-4 pr-5"><Smartphone size={20}/><div><h3 className="font-display font-bold text-sm">Install STRYVEN</h3><p className="text-xs text-slate-400">Add to your home screen</p></div></div><p className="text-sm text-slate-300 leading-5">{isIOS?'Tap Share in Safari, then choose “Add to Home Screen”.':'Your browser did not expose the automatic install prompt. Use the browser menu or address-bar install icon to add STRYVEN to your device.'}</p><button onClick={closeInstructions} className="btn-ghost w-full mt-5">Got it</button></div></motion.div>}</AnimatePresence>
  <AnimatePresence>{showSuccess&&<motion.div initial={{opacity:0,y:-20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}} className="fixed top-3 left-1/2 -translate-x-1/2 z-[100] w-[min(22rem,calc(100vw-1.5rem))]"><div className="flex items-center gap-2.5 px-4 py-3 rounded-2xl border border-emerald-500/30 bg-emerald-500/10 backdrop-blur-xl"><CheckCircle2 size={18} className="text-emerald-400 shrink-0"/><span className="text-sm font-semibold text-emerald-300 truncate">STRYVEN installed successfully!</span></div></motion.div></AnimatePresence>
 </>;
}
