import { useEffect,useMemo,useRef,useState } from 'react';
import { Crown,Shield,Users,Trophy,Target,Upload,Search,UserPlus,LogOut,Settings2,Check,X,RefreshCw,Swords } from 'lucide-react';
import { useAuth } from '../lib/auth';
import { supabase,isSupabaseConfigured } from '../lib/supabase';
import { toast } from '../components/ui/Toast';

type Role='member'|'officer'|'leader';
type Clan={id:string;name:string;emblem:string;image_url:string|null;description:string|null;leader_id:string;level:number;xp:number;max_members:number};
type Member={clan_id:string;user_id:string;role:Role;joined_at:string;contribution_xp:number;username?:string;avatar?:string};
type Mission={id:string;title:string;description:string|null;target:number;progress:number;xp_reward:number;ends_at:string|null;completed_at:string|null};
type History={id:string;event_type:string;title:string;details:string|null;created_at:string};
type Request={id:string;user_id:string;created_at:string;username?:string;avatar?:string};
type Found={id:string;name:string;emblem:string;image_url:string|null;level:number;xp:number;max_members:number;member_count:number};
const EMBLEMS=['⚔️','🐺','🔥','☠️','🛡️','👁️','🐉','🩸','🌑','⚡','🦅','👑'];

export function ClansRebuilt(){
 const {user}=useAuth();const [clan,setClan]=useState<Clan|null>(null);const [members,setMembers]=useState<Member[]>([]);const [missions,setMissions]=useState<Mission[]>([]);const [history,setHistory]=useState<History[]>([]);const [requests,setRequests]=useState<Request[]>([]);const [season,setSeason]=useState<any>(null);const [seasonXp,setSeasonXp]=useState(0);const [seasonRank,setSeasonRank]=useState<number|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [tab,setTab]=useState<'overview'|'members'|'missions'|'history'>('overview');const [manage,setManage]=useState(false);const [newName,setNewName]=useState('');const [name,setName]=useState('');const [description,setDescription]=useState('');const [emblem,setEmblem]=useState('⚔️');const [query,setQuery]=useState('');const [found,setFound]=useState<Found[]>([]);const fileRef=useRef<HTMLInputElement>(null);
 const me=members.find(m=>m.user_id===user?.id);const isLeader=!!clan&&clan.leader_id===user?.id;const isManager=me?.role==='leader'||me?.role==='officer';const progress=useMemo(()=>Math.min(100,(Number(clan?.xp??0)%1000)/10),[clan?.xp]);
 const load=async()=>{if(!user||!isSupabaseConfigured()){setLoading(false);return}setLoading(true);try{const {data:memb,error:e}=await supabase.from('clan_members').select('clan_id,user_id,role,joined_at,contribution_xp').eq('user_id',user.id).maybeSingle();if(e)throw e;if(!memb){setClan(null);setMembers([]);setMissions([]);setHistory([]);setRequests([]);setLoading(false);return}const [{data:c,error:ce},{data:ms,error:me2},{data:mi,error:mie},{data:h,error:he},{data:r,error:re},{data:s,error:se}]=await Promise.all([supabase.from('clans').select('id,name,emblem,image_url,description,leader_id,level,xp,max_members').eq('id',memb.clan_id).single(),supabase.from('clan_members').select('*').eq('clan_id',memb.clan_id).order('role',{ascending:false}),supabase.from('clan_missions').select('id,title,description,target,progress,xp_reward,ends_at,completed_at').eq('clan_id',memb.clan_id).order('completed_at',{ascending:true,nullsFirst:true}).limit(20),supabase.from('clan_history').select('id,event_type,title,details,created_at').eq('clan_id',memb.clan_id).order('created_at',{ascending:false}).limit(40),supabase.from('clan_join_requests').select('id,user_id,created_at').eq('clan_id',memb.clan_id).eq('status','pending').order('created_at'),supabase.from('seasons').select('id,season_number,name').eq('status','active').order('season_number',{ascending:false}).limit(1).maybeSingle()]);if(ce||me2||mie||he||re||se)throw ce||me2||mie||he||re||se;const raw=(ms??[]) as Member[];const ids=raw.map(x=>x.user_id);const {data:profiles}=ids.length?await supabase.from('profiles').select('id,username,avatar').in('id',ids):{data:[] as any[]};const pm=new Map((profiles??[]).map((p:any)=>[p.id,p]));const rr=(r??[]) as Request[];const rids=rr.map(x=>x.user_id);const {data:rprofiles}=rids.length?await supabase.from('profiles').select('id,username,avatar').in('id',rids):{data:[] as any[]};const rpm=new Map((rprofiles??[]).map((p:any)=>[p.id,p]));setClan(c as Clan);setName((c as Clan).name);setDescription((c as Clan).description??'');setEmblem((c as Clan).emblem||'⚔️');setMembers(raw.map(x=>({...x,username:pm.get(x.user_id)?.username,avatar:pm.get(x.user_id)?.avatar})));setMissions((mi??[]) as Mission[]);setHistory((h??[]) as History[]);setRequests(rr.map(x=>({...x,username:rpm.get(x.user_id)?.username,avatar:rpm.get(x.user_id)?.avatar})));if(s){setSeason(s);const {data:score}=await supabase.from('clan_season_scores').select('xp,rank').eq('season_id',s.id).eq('clan_id',memb.clan_id).maybeSingle();setSeasonXp(Number(score?.xp??0));setSeasonRank(score?.rank??null)}else{setSeason(null);setSeasonXp(0);setSeasonRank(null)}}catch(e){console.error(e);toast({title:'Could not load clan',type:'error'})}finally{setLoading(false)}};
 useEffect(()=>{void load()},[user?.id]);
 const create=async()=>{const n=newName.trim();if(!user)return;if(n.length<3||n.length>28){toast({title:'Clan name must be 3–28 characters',type:'error'});return}setBusy(true);try{const {data,error}=await supabase.from('clans').insert({name:n,leader_id:user.id,emblem}).select('id').single();if(error)throw error;await supabase.rpc('create_default_clan_mission',{p_clan_id:data.id});toast({title:'Clan founded',type:'success'});setNewName('');await load()}catch(e:any){toast({title:e?.code==='23505'?'Clan name already taken':'Could not create clan',type:'error'})}finally{setBusy(false)}};
 const save=async()=>{if(!clan||!isLeader)return;setBusy(true);const {error}=await supabase.from('clans').update({name:name.trim(),description:description.trim(),emblem,updated_at:new Date().toISOString()}).eq('id',clan.id);setBusy(false);if(error)toast({title:'Could not save clan',type:'error'});else{toast({title:'Clan settings saved',type:'success'});setManage(false);await load()}};
 const upload=async(file:File)=>{if(!clan||!isLeader)return;if(!file.type.startsWith('image/')||file.size>3*1024*1024){toast({title:'Use an image under 3 MB',type:'error'});return}setBusy(true);try{const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${clan.id}/${Date.now()}.${ext}`;const {error:e}=await supabase.storage.from('clan-images').upload(path,file,{upsert:true,cacheControl:'3600'});if(e)throw e;const {data}=supabase.storage.from('clan-images').getPublicUrl(path);const {error}=await supabase.from('clans').update({image_url:data.publicUrl,updated_at:new Date().toISOString()}).eq('id',clan.id);if(error)throw error;toast({title:'Clan image updated',type:'success'});await load()}catch(e){console.error(e);toast({title:'Could not upload image',type:'error'})}finally{setBusy(false)}};
 const searchClans=async()=>{const q=query.trim();if(q.length<2){setFound([]);return}const {data,error}=await supabase.from('clans').select('id,name,emblem,image_url,level,xp,max_members,clan_members(count)').ilike('name',`%${q}%`).limit(12);if(error){toast({title:'Clan search failed',type:'error'});return}setFound((data??[]).map((x:any)=>({...x,member_count:Number(x.clan_members?.[0]?.count??0)})))};
 const request=async(id:string)=>{if(!user)return;const {error}=await supabase.from('clan_join_requests').insert({clan_id:id,user_id:user.id});if(error)toast({title:error.code==='23505'?'Request already sent':'Could not send request',type:'error'});else toast({title:'Join request sent',type:'success'})};
 const accept=async(id:string)=>{setBusy(true);const {error}=await supabase.rpc('accept_join_request',{p_request_id:id});setBusy(false);if(error)toast({title:error.message==='clan_full'?'Clan is full':'Could not accept request',type:'error'});else await load()};const decline=async(id:string)=>{const {error}=await supabase.rpc('decline_join_request',{p_request_id:id});if(error)toast({title:'Could not decline request',type:'error'});else await load()};const changeRole=async(m:Member)=>{if(!clan||!isLeader)return;const r=m.role==='officer'?'member':'officer';const {error}=await supabase.rpc('set_clan_member_role',{p_clan_id:clan.id,p_user_id:m.user_id,p_role:r});if(error)toast({title:'Could not change role',type:'error'});else await load()};const kick=async(m:Member)=>{if(!clan||!isManager||m.role==='leader'||m.user_id===user?.id)return;if(!confirm(`Remove ${m.username??'this hunter'}?`))return;const {error}=await supabase.rpc('kick_clan_member',{p_clan_id:clan.id,p_user_id:m.user_id});if(error)toast({title:'Could not remove member',type:'error'});else await load()};const leave=async()=>{if(!clan||isLeader||!confirm('Leave this clan?'))return;const {error}=await supabase.rpc('leave_clan',{p_clan_id:clan.id});if(error)toast({title:'Could not leave clan',type:'error'});else await load()};
 if(!user)return <Empty text="Sign in to access Clans."/>;if(loading)return <Loading/>;if(!clan)return <div className="space-y-6 pb-8"><Card title="Find Your Clan" icon={Shield}><p className="text-sm text-ink-400">Join an existing squad or found your own. Clan XP is tied to real member seasonal XP.</p><div className="mt-5 flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void searchClans()} placeholder="Search clan name..." className="input flex-1"/><button onClick={()=>void searchClans()} className="btn-primary"><Search size={15}/> Search</button></div><div className="mt-3 space-y-2">{found.map(c=><div key={c.id} className="flex items-center gap-3 rounded-xl border border-white/5 bg-white/[.02] p-3"><ClanPic url={c.image_url} emblem={c.emblem}/><div className="min-w-0 flex-1"><p className="truncate font-semibold">{c.emblem} {c.name}</p><p className="text-[10px] text-ink-600">Level {c.level} · {c.member_count}/{c.max_members}</p></div><button onClick={()=>void request(c.id)} className="btn-ghost text-xs"><UserPlus size={14}/> Request</button></div>)}</div></Card><Card title="Create a Clan" icon={Crown}><div className="flex flex-col gap-3 sm:flex-row"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Clan name" className="input flex-1"/><button disabled={busy} onClick={()=>void create()} className="btn-primary"><Crown size={15}/> Found Clan</button></div><Emblems value={emblem} setValue={setEmblem}/></Card></div>;
 return <div className="space-y-5 pb-8"><section className="relative overflow-hidden rounded-[1.75rem] border border-white/10 bg-ink-950/70"><div className="h-44 bg-cover bg-center" style={clan.image_url?{backgroundImage:`url("${clan.image_url}")`}:{}}><div className="h-full bg-gradient-to-t from-ink-950 via-ink-950/50 to-transparent"/></div><div className="relative -mt-12 px-5 pb-6 sm:px-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end"><ClanPic url={clan.image_url} emblem={clan.emblem} large/><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-[.25em] text-ember-400">{isLeader?'Leader':'Clan'} Command</p><h1 className="mt-1 truncate font-display text-3xl font-black uppercase">{clan.name}</h1><p className="mt-1 text-sm text-ink-400">{clan.description||'A squad forged through discipline.'}</p></div>{isLeader&&<button onClick={()=>setManage(v=>!v)} className="btn-ghost"><Settings2 size={15}/> Manage</button>}</div></div></section>
 {manage&&isLeader&&<Card title="Clan Settings" icon={Settings2}><div className="grid gap-4 md:grid-cols-2"><div><input value={name} onChange={e=>setName(e.target.value)} className="input w-full" placeholder="Clan name"/><textarea value={description} onChange={e=>setDescription(e.target.value)} className="input mt-3 min-h-24 w-full" placeholder="Description"/></div><div><Emblems value={emblem} setValue={setEmblem}/><button disabled={busy} onClick={()=>fileRef.current?.click()} className="btn-ghost mt-3"><Upload size={15}/> Change Clan Image</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.currentTarget.value=''}}/><p className="mt-2 text-[10px] text-ink-600">Only the Leader can change clan identity.</p></div></div><button disabled={busy} onClick={()=>void save()} className="btn-primary mt-4"><Check size={15}/> Save</button></Card>}
 <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat icon={Shield} label="Level" value={String(clan.level)}/><Stat icon={Trophy} label="Clan XP" value={clan.xp.toLocaleString()}/><Stat icon={Users} label="Members" value={`${members.length}/${clan.max_members}`}/><Stat icon={Target} label="Season Rank" value={seasonRank?`#${seasonRank}`:'—'}/></div><Card title="Clan Progress" icon={Target}><div className="flex justify-between text-xs text-ink-500"><span>Level {clan.level}</span><span>{clan.xp%1000}/1000 XP</span></div><div className="mt-2 h-2 rounded-full bg-ink-900"><div className="h-full rounded-full bg-gradient-to-r from-ember-500 to-gold-500" style={{width:`${progress}%`}}/></div><p className="mt-2 text-[10px] text-ink-600">Season contribution: {seasonXp.toLocaleString()} XP · {season?.name||'No active season'}</p></Card>
 <div className="rounded-2xl border border-white/10 bg-black/25 p-1"><div className="grid grid-cols-4 gap-1">{(['overview','members','missions','history'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-2 py-3 text-[10px] font-black uppercase tracking-widest ${tab===t?'bg-ember-500/15 text-ember-400':'text-ink-500'}`}>{t}</button>)}</div></div>
 {tab==='overview'&&<div className="grid gap-4 md:grid-cols-2"><Card title="Active Mission" icon={Target}>{missions.find(m=>!m.completed_at)?<MissionRow mission={missions.find(m=>!m.completed_at)!}/>:<p className="text-sm text-ink-500">No active mission.</p>}</Card><Card title="Season" icon={Trophy}><p className="font-display text-3xl font-black">#{seasonRank??'—'}</p><p className="mt-1 text-xs text-ink-500">{seasonXp.toLocaleString()} real clan XP</p></Card></div>}
 {tab==='members'&&<Card title={`Members · ${members.length}`} icon={Users}>{isManager&&requests.length>0&&<div className="mb-4 rounded-xl border border-ember-500/20 bg-ember-500/[.04] p-3"><p className="mb-2 text-[10px] font-black uppercase tracking-widest text-ember-400">Join Requests</p>{requests.map(r=><div key={r.id} className="flex items-center gap-2 border-t border-white/5 py-2"><Avatar value={r.avatar}/><span className="flex-1 truncate text-sm">{r.username||'Hunter'}</span><button onClick={()=>void accept(r.id)} className="btn-ghost text-xs text-emerald-400"><Check size={14}/></button><button onClick={()=>void decline(r.id)} className="btn-ghost text-xs"><X size={14}/></button></div>)}</div>}{members.map(m=><div key={m.user_id} className="flex items-center gap-3 border-b border-white/5 py-3 last:border-0"><Avatar value={m.avatar}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{m.username||'Hunter'}</p><p className="text-[10px] uppercase tracking-wider text-ink-600">{m.role} · {m.contribution_xp.toLocaleString()} contribution XP</p></div>{m.role==='leader'&&<Crown size={15} className="text-gold-400"/>}{isLeader&&m.role!=='leader'&&<button onClick={()=>void changeRole(m)} className="btn-ghost text-[10px]">{m.role==='officer'?'Demote':'Officer'}</button>}{isManager&&m.role==='member'&&<button onClick={()=>void kick(m)} className="btn-ghost text-[10px] text-red-400">Remove</button>}</div>)}{!isLeader&&<button onClick={()=>void leave()} className="btn-ghost mt-4 text-xs text-red-400"><LogOut size={14}/> Leave Clan</button>}</Card>}
 {tab==='missions'&&<Card title="Clan Missions" icon={Target}>{missions.length?missions.map(m=><MissionRow key={m.id} mission={m}/>):<p className="text-sm text-ink-500">No missions yet.</p>}</Card>}{tab==='history'&&<Card title="Clan History" icon={Swords}>{history.length?history.map(h=><div key={h.id} className="border-b border-white/5 py-3 last:border-0"><p className="text-sm font-semibold">{h.title}</p><p className="mt-1 text-xs text-ink-500">{h.details||h.event_type} · {new Date(h.created_at).toLocaleString()}</p></div>):<p className="text-sm text-ink-500">No history yet.</p>}</Card>}
 </div>;
}
function MissionRow({mission}:{mission:Mission}){const pct=Math.min(100,Math.round(mission.progress/Math.max(1,mission.target)*100));return <div className="rounded-xl border border-white/5 bg-white/[.02] p-3"><div className="flex justify-between gap-3"><div><p className="font-semibold">{mission.title}</p><p className="mt-1 text-xs text-ink-500">{mission.description}</p></div><span className="font-mono text-xs text-ember-400">+{mission.xp_reward} XP</span></div><div className="mt-3 h-1.5 rounded-full bg-ink-900"><div className="h-full rounded-full bg-ember-500" style={{width:`${pct}%`}}/></div><p className="mt-2 text-[10px] text-ink-600">{mission.progress}/{mission.target} · {mission.completed_at?'COMPLETED':'ACTIVE'}</p></div>}
function Emblems({value,setValue}:{value:string;setValue:(x:string)=>void}){return <div className="mt-3 flex flex-wrap gap-2">{EMBLEMS.map(e=><button key={e} onClick={()=>setValue(e)} className={`h-9 w-9 rounded-lg border ${value===e?'border-ember-500/50 bg-ember-500/10':'border-white/10 bg-black/20'}`}>{e}</button>)}</div>}
function ClanPic({url,emblem,large=false}:{url:string|null|undefined;emblem:string|undefined;large?:boolean}){return <div className={`${large?'h-20 w-20 text-3xl':'h-10 w-10 text-lg'} flex shrink-0 items-center justify-center overflow-hidden rounded-2xl border border-white/10 bg-black/60 shadow-xl`}>{url?<img src={url} alt="Clan" className="h-full w-full object-cover"/>:<span>{emblem||'⚔️'}</span>}</div>}
function Avatar({value}:{value?:string}){return <div className="h-9 w-9 shrink-0 overflow-hidden rounded-full border border-white/10 bg-black/30">{value&&<img src={value} alt="" className="h-full w-full object-cover"/>}</div>}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-black/25 p-4"><Icon size={15} className="text-ember-400"/><p className="mt-3 font-display text-xl font-black">{value}</p><p className="text-[10px] uppercase tracking-wider text-ink-600">{label}</p></div>}
function Card({title,icon:Icon,children}:{title:string;icon:any;children:any}){return <section className="rounded-[1.5rem] border border-white/10 bg-black/25 p-5"><div className="mb-4 flex items-center gap-2"><Icon size={16} className="text-ember-400"/><h2 className="font-display text-lg font-black uppercase">{title}</h2></div>{children}</section>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-white/10 bg-black/25 p-10 text-center text-sm text-ink-500">{text}</div>}
function Loading(){return <div className="rounded-2xl border border-white/10 bg-black/25 p-12 text-center"><RefreshCw size={24} className="mx-auto mb-3 animate-spin text-ember-400"/><p className="text-sm text-ink-400">Synchronizing clan command...</p></div>}
