import { useMemo, useState } from 'react';
import { useStore } from '../store/useStore';
import { getRankByXp, getRankIndex, RANKS } from '../data/ranks';
import { DUNGEONS, type Dungeon } from '../data/dungeons';
import { Modal } from '../components/ui/Modal';
import { toast } from '../components/ui/Toast';
import { triggerConfetti } from '../components/ui/Confetti';
import { playSound } from '../lib/sound';
import { Swords, Lock, Check, Zap, Trophy, Dumbbell, X, ChevronRight, Skull, Target, Crown, ShieldAlert, Gauge, RotateCcw } from 'lucide-react';
import '../stryven-dungeons.css';
import '../dungeons-performance.css';

const DUNGEON_IMAGES: Record<string, string> = {
  'Awakening Gate': '/awakening-gate.webp.jpg','Whispering Hollow': '/whispering-hollow.webp.jpg','Stone Trial': '/stone-trial.webp.jpg','Frost Cavern': '/frost-cavern.webp.jpg','Storm Spire': '/storm-spire.webp.jpg','Crimson Sanctum': '/crimson-sanctum.webp.jpg','Inferno Keep': '/inferno-keep.webp.jpg','Thunder Vault': '/thunder-vault.webp.jpg','Dark Abyss': '/dark-abyss.webp.jpg','Shadow Labyrinth': '/shadow-labyrinth.webp.jpg',"Hunter's Gauntlet": '/hunters-gauntlet.webp.jpg',"Monarch's Throne": '/monarchs-throne.webp.jpg',"Slayer's Coliseum": '/slayers-coliseum.webp.jpg','Nightmare Sanctum': '/nightmare-sanctum.webp.jpg','Doom Crucible': '/doom-crucible.webp.jpg',"Executioner's Block": '/executioners-block.webp.jpg','Mythic Sanctuary': '/mythic-sanctuary.webp.jpg','Hall of the Immortal': '/hall-of-the-immortal.webp.jpg',"Shadow King's Court": '/shadow-kings-court.webp.jpg','System Overlord Citadel': '/system-overlord-citadel.webp.jpg',
};

function difficulty(index: number) { if (index < 4) return 'CALIBRATION'; if (index < 8) return 'HARD'; if (index < 12) return 'SEVERE'; if (index < 16) return 'NIGHTMARE'; return 'APEX'; }

export function Dungeons() {
  const { state, clearDungeon } = useStore();
  const [selected, setSelected] = useState<Dungeon | null>(null);
  const [active, setActive] = useState<Dungeon | null>(null);
  const [done, setDone] = useState<Record<number, boolean>>({});
  const [reward, setReward] = useState<{ dungeon: Dungeon; awardedXp: number } | null>(null);
  const [finishing, setFinishing] = useState(false);
  const rank = getRankByXp(state.xp);
  const rankIndex = getRankIndex(rank.id);
  const cleared = state.dungeonClearedToday;
  const remainingXp = Math.max(0, state.dailyCap - state.dailyXp);
  const clearedCount = state.dungeonsCleared ?? 0;
  const progress = active ? Math.round((Object.values(done).filter(Boolean).length / Math.max(1, active.exercises.length)) * 100) : 0;
  const unlockedCount = useMemo(() => DUNGEONS.filter((d) => getRankIndex(d.rankId) <= rankIndex).length, [rankIndex]);

  const enter = (dungeon: Dungeon) => { if (cleared) { toast({ title: 'Raid already cleared', message: 'Your daily raid is complete. Return after the daily reset.', type: 'info' }); return; } setSelected(null); setActive(dungeon); setDone({}); playSound('whoosh'); };
  const finish = () => { if (!active || finishing || cleared) return; if (Object.values(done).filter(Boolean).length !== active.exercises.length) return; setFinishing(true); const before = state.dailyXp; clearDungeon(active.id); const awardedXp = Math.max(0, Math.min(active.rewardXp, state.dailyCap - before)); setActive(null); setReward({ dungeon: active, awardedXp }); setFinishing(false); triggerConfetti(60); playSound('reward'); toast({ title: 'Raid cleared', message: `+${awardedXp.toLocaleString()} XP progression secured.`, type: 'success' }); };

  return (
    <div className="stryven-raids">
      <section className="raid-hero"><div className="raid-hero__image"/><div className="raid-hero__veil"/><div className="raid-hero__content"><div className="raid-kicker"><span className="raid-kicker__line"/> DAILY RAID <span className="raid-kicker__line"/></div><h1 className="raid-title">THE DUNGEONS</h1><p className="raid-subtitle">Twenty escalating trials. One hunter. Enter the path, complete every objective, and secure progression.</p><div className="raid-status-row"><div className="raid-status"><Target size={15}/><span>RANK</span><strong>{rank.name}</strong></div><div className="raid-status"><ShieldAlert size={15}/><span>UNLOCKED</span><strong>{unlockedCount} / {DUNGEONS.length}</strong></div><div className={`raid-status ${cleared ? 'is-cleared' : ''}`}><Swords size={15}/><span>DAILY RAID</span><strong>{cleared ? 'CLEARED' : 'READY'}</strong></div></div></div></section>
      <section className="raid-section-head"><div><div className="raid-section-kicker">THE RAID PATH</div><h2>Choose your dungeon</h2></div><div className="raid-count">{clearedCount} <span>COMPLETED</span></div></section>
      <section className="raid-rail" aria-label="Dungeon raids">{DUNGEONS.map((dungeon, index) => { const requiredRankIndex = getRankIndex(dungeon.rankId); const unlocked = requiredRankIndex <= rankIndex; const current = requiredRankIndex === rankIndex; const requiredRank = RANKS.find((item) => item.id === dungeon.rankId)!; const lockedByDaily = cleared && current; return <button key={dungeon.id} className={`raid-card ${current ? 'is-current' : ''} ${!unlocked ? 'is-locked' : ''} ${lockedByDaily ? 'is-cleared' : ''}`} style={{ ['--rank-color' as any]: requiredRank.color, ['--delay' as any]: `${Math.min(index * 30, 450)}ms` }} onClick={() => unlocked && !lockedByDaily && setSelected(dungeon)} disabled={!unlocked || lockedByDaily} aria-label={`${dungeon.name}, ${unlocked ? 'unlocked' : 'locked'}, ${dungeon.rewardXp} XP`}><img src={DUNGEON_IMAGES[dungeon.name]} alt="" className="raid-card__image" loading={index < 2 ? 'eager' : 'lazy'} decoding="async"/><span className="raid-card__shade"/><span className="raid-card__top"><span className="raid-card__number">{String(index + 1).padStart(2, '0')}</span><span className="raid-card__rank">{requiredRank.name}</span></span><span className="raid-card__bottom"><span className="raid-card__theme">{dungeon.theme}</span><strong>{dungeon.name}</strong><span className="raid-card__meta"><Zap size={11}/> {dungeon.rewardXp.toLocaleString()} XP <i/> {dungeon.exercises.length} OBJECTIVES <i/> {difficulty(index)}</span></span>{!unlocked && <span className="raid-card__lock"><Lock size={18}/><small>LOCKED</small><em>Requires {requiredRank.name}</em></span>}{lockedByDaily && <span className="raid-card__clear"><Check size={13}/> CLEARED TODAY</span>}</button>; })}</section>
      <div className="raid-scroll-hint"><ChevronRight size={14}/> DRAG OR SHIFT + SCROLL TO EXPLORE ALL RAIDS <ChevronRight size={14}/></div>
      <section className="raid-footer-panel"><div className="raid-footer-art"/><div className="raid-footer-copy"><span>THE RAID PROTOCOL</span><strong>One clear per day.<br/>No currency. No inventory. XP only.</strong></div><div className="raid-footer-stats"><div><Skull size={17}/><b>20</b><span>RAIDS</span></div><div><Crown size={17}/><b>APEX</b><span>FINAL TIER</span></div><div><Trophy size={17}/><b>{clearedCount}</b><span>TOTAL CLEARS</span></div></div></section>
      <Modal open={!!selected} onClose={() => setSelected(null)} title="" size="lg">{selected && <Preview dungeon={selected} rank={rank} rankIndex={rankIndex} dailyRemainingXp={remainingXp} onEnter={enter}/>}</Modal>
      <Modal open={!!active} onClose={() => !finishing && setActive(null)} title="" size="md">{active && <div className="raid-run-modal"><div className="raid-run-art" style={{ backgroundImage: `url(${DUNGEON_IMAGES[active.name]})` }}><div><span>RAID IN PROGRESS</span><strong>{active.name}</strong></div><button onClick={() => setActive(null)} disabled={finishing} aria-label="Close"><X size={18}/></button></div><div className="raid-run-body"><p className="raid-run-copy">Complete every objective. Each objective can only be claimed once per run.</p><div className="raid-progress"><span style={{ width: `${progress}%` }}/></div><div className="raid-exercises">{active.exercises.map((exercise, index) => { const isDone = !!done[index]; return <button key={`${active.id}-${index}`} disabled={isDone || finishing} onClick={() => { setDone((currentDone) => ({ ...currentDone, [index]: true })); playSound('task'); }} className={isDone ? 'done' : ''}><span className="raid-exercise-check">{isDone && <Check size={13}/>}</span><Dumbbell size={16}/><span>{exercise.name}</span><b>{exercise.reps}{exercise.isTime ? 's' : ' reps'}</b></button>; })}</div><button disabled={progress < 100 || finishing} onClick={finish} className="raid-claim"><Trophy size={17}/>{finishing ? 'SECURING...' : `CLAIM ${active.rewardXp.toLocaleString()} XP`}</button></div></div>}</Modal>
      <Modal open={!!reward} onClose={() => setReward(null)} title="" size="md">{reward && <div className="raid-reward-modal"><div className="raid-reward-art" style={{ backgroundImage: `url(${DUNGEON_IMAGES[reward.dungeon.name]})` }}><div className="raid-reward-badge"><Trophy size={27}/></div></div><div className="raid-reward-body"><span>RAID CLEARED</span><h3>{reward.dungeon.name}</h3><div className="raid-reward-list"><div className="raid-reward-display" style={{ ['--reward-color' as any]: '#f2a33a' }}><div><Zap size={17}/></div><span>+{reward.awardedXp.toLocaleString()} XP</span><b>PROGRESSION</b></div></div><button onClick={() => setReward(null)} className="raid-continue">CONTINUE</button></div></div>}</Modal>
    </div>
  );
}

function Preview({ dungeon, rank, rankIndex, dailyRemainingXp, onEnter }: { dungeon: Dungeon; rank: ReturnType<typeof getRankByXp>; rankIndex: number; dailyRemainingXp: number; onEnter: (dungeon: Dungeon) => void }) {
  const requiredRankIndex = getRankIndex(dungeon.rankId); const requiredRank = RANKS.find((item) => item.id === dungeon.rankId)!; const canEnter = requiredRankIndex <= rankIndex && dailyRemainingXp > 0; const effectiveXp = Math.min(dungeon.rewardXp, dailyRemainingXp);
  return <div className="raid-preview"><div className="raid-preview__art" style={{ backgroundImage: `url(${DUNGEON_IMAGES[dungeon.name]})` }}><div className="raid-preview__overlay"/><div className="raid-preview__title"><span>{dungeon.theme}</span><h3>{dungeon.name}</h3><p>{dungeon.description}</p></div></div><div className="raid-preview__body"><div className="raid-preview__stats"><div><Zap size={15}/><span>XP REWARD</span><b>{effectiveXp.toLocaleString()}</b></div><div><Target size={15}/><span>OBJECTIVES</span><b>{dungeon.exercises.length}</b></div><div><Crown size={15}/><span>REQUIRED</span><b>{requiredRank.name}</b></div></div><div className="raid-preview__label">TRIAL REQUIREMENTS</div><div className="raid-preview__exercises">{dungeon.exercises.map((exercise, index) => <div key={index}><Dumbbell size={15}/><span>{exercise.name}</span><b>{exercise.reps}{exercise.isTime ? 's' : ' reps'}</b></div>)}</div><div className="raid-preview__label">RUN CONDITIONS</div><div className="raid-preview__exercises"><div><Gauge size={15}/><span>Difficulty</span><b>{difficulty(DUNGEONS.findIndex((item) => item.id === dungeon.id))}</b></div><div><RotateCcw size={15}/><span>Daily limit</span><b>1 clear</b></div><div><Zap size={15}/><span>XP cap room</span><b>{dailyRemainingXp.toLocaleString()}</b></div></div><div className="raid-preview__label">REWARD</div><div className="raid-preview__rewards"><div className="raid-reward-chip" style={{ ['--reward-color' as any]: '#f2a33a' }}><Zap size={14}/><span>+{effectiveXp.toLocaleString()} XP</span></div></div><button onClick={() => onEnter(dungeon)} disabled={!canEnter} className="raid-enter"><Swords size={17}/>{dailyRemainingXp <= 0 ? 'DAILY XP CAP REACHED' : canEnter ? 'ENTER RAID' : `REQUIRES ${requiredRank.name}`}</button></div></div>;
}
