import { useEffect, useRef, useState } from 'react';
import { useStore } from '../store/useStore';
import { useAuth } from '../lib/auth';
import { ConfirmModal } from '../components/ui/Modal';
import { BACKGROUNDS, AURAS } from '../data/collections';
import { getRankByXp } from '../data/ranks';
import { RankBadge } from '../components/ui/RankBadge';
import { Upload, Trash2, Volume2, VolumeX, Palette, User as UserIcon, Image as ImageIcon, Video, Sparkles, LogOut, Moon, Shield, Eye, Cloud, RotateCcw, Settings as SettingsIcon, Check, SlidersHorizontal } from 'lucide-react';
import { toast } from '../components/ui/Toast';
import { playSound } from '../lib/sound';
import { uploadBackground } from '../lib/backgroundUpload';

type BgType='default'|'image'|'video'|'animated';
const NAME_COLORS=['#f5f5f7','#d62b4d','#9f1830','#6e55b5','#426b9c','#9b9ba4'];
const BANNER_COLORS=['#050507','#10070b','#0a0a12','#0b0e16','#120b0f','#09090e'];
const ALLOWED_IMAGE_TYPES=['image/jpeg','image/png','image/webp','image/gif'];
const ALLOWED_VIDEO_TYPES=['video/mp4','video/webm','video/ogg'];

export function Settings(){
 const {state,updateProfile,setCustomBackground,setBackgroundVideo,setBackgroundType,setBackgroundBlur,setBackgroundDarken,setBackgroundBrightness,setSelectedBackground,toggleSound,resetAll,syncLeaderboard}=useStore();
 const {signOut,user}=useAuth();
 const [resetOpen,setResetOpen]=useState(false); const [logoutOpen,setLogoutOpen]=useState(false); const [uploading,setUploading]=useState(false);
 const [reducedMotion,setReducedMotion]=useState(()=>localStorage.getItem('stryven-reduced-motion')==='1');
 const [compact,setCompact]=useState(()=>localStorage.getItem('stryven-compact')==='1');
 const imageRef=useRef<HTMLInputElement>(null); const videoRef=useRef<HTMLInputElement>(null); const mounted=useRef(true);
 const rank=getRankByXp(state.xp); const aura=state.equipped.aura?AURAS.find(a=>a.id===state.equipped.aura):null;
 useEffect(()=>()=>{mounted.current=false},[]);
 useEffect(()=>{document.documentElement.classList.toggle('sv-reduced-motion',reducedMotion);localStorage.setItem('stryven-reduced-motion',reducedMotion?'1':'0')},[reducedMotion]);
 useEffect(()=>{document.documentElement.classList.toggle('sv-compact',compact);localStorage.setItem('stryven-compact',compact?'1':'0')},[compact]);
 const setMotion=(value:boolean)=>{setReducedMotion(value);toast({title:value?'Reduced motion enabled':'Reduced motion disabled',type:'success'})};
 const setDensity=(value:boolean)=>{setCompact(value);toast({title:value?'Compact mode enabled':'Compact mode disabled',type:'success'})};
 const handleUpload=async(event:React.ChangeEvent<HTMLInputElement>,kind:'image'|'video')=>{const file=event.target.files?.[0];if(!file)return;const max=kind==='image'?10:50;const allowed=kind==='image'?ALLOWED_IMAGE_TYPES:ALLOWED_VIDEO_TYPES;if(file.size>max*1024*1024){toast({title:'File too large',message:`Maximum ${max}MB.`,type:'error'});event.target.value='';return}if(!allowed.includes(file.type)){toast({title:'Invalid file type',message:kind==='image'?'Use JPG, PNG, WebP, or GIF.':'Use MP4, WebM, or OGG.',type:'error'});event.target.value='';return}setUploading(true);try{if(user){const {url,error}=await uploadBackground(user.id,file,kind);if(error||!url)throw new Error(error||'Upload failed');if(!mounted.current)return;if(kind==='image')setCustomBackground(url);else setBackgroundVideo(url);setBackgroundType(kind)}else{const reader=new FileReader();await new Promise<void>((resolve,reject)=>{reader.onload=()=>{if(!mounted.current){resolve();return}if(kind==='image')setCustomBackground(reader.result as string);else setBackgroundVideo(reader.result as string);setBackgroundType(kind);resolve()};reader.onerror=()=>reject(reader.error||new Error('Could not read file'));reader.readAsDataURL(file)});}toast({title:`${kind==='image'?'Image':'Video'} background applied`,type:'success'})}catch(error){toast({title:'Upload failed',message:error instanceof Error?error.message:'Unknown error',type:'error'})}finally{if(mounted.current)setUploading(false);event.target.value=''}};
 const selectPreset=(id:string)=>{const selected=state.selectedBackgroundId===id;setSelectedBackground(selected?null:id);setCustomBackground(null);setBackgroundVideo(null);setBackgroundType(selected?'default':'animated');toast({title:selected?'Default environment restored':'Environment applied',type:'success'})};
 const selectBgType=(type:BgType)=>{if(type==='image'&&!state.customBackground){imageRef.current?.click();return}if(type==='video'&&!state.backgroundVideo){videoRef.current?.click();return}setBackgroundType(type);toast({title:`${type.toUpperCase()} environment selected`,type:'success'})};
 const clearEnvironment=()=>{setCustomBackground(null);setBackgroundVideo(null);setSelectedBackground(null);setBackgroundType('default');setBackgroundBrightness(100);setBackgroundBlur(0);setBackgroundDarken(0);toast({title:'Environment reset',type:'success'})};
 const signOutNow=async()=>{playSound('click');await signOut()};
 return <div className="sv-settings-v3">
  <header className="sv-config-hero"><div><div className="sv-config-kicker"><span className="sv-status-dot"/> STRYVEN / SYSTEM CONFIGURATION</div><h1>CONTROL<br/><em>THE SYSTEM.</em></h1><p>Configure your identity, interface, environment, audio and session without leaving the system.</p></div><div className="sv-config-rank"><RankBadge rank={rank} size="sm" auraColor={aura?.color}/><div><span>CURRENT RANK</span><b style={{color:rank.color}}>{rank.name}</b><small>{state.xp.toLocaleString()} XP</small></div></div></header>
  <div className="sv-config-layout">
   <aside className="sv-config-index"><span>CONFIG INDEX</span><a href="#identity">01 IDENTITY</a><a href="#interface">02 INTERFACE</a><a href="#environment">03 ENVIRONMENT</a><a href="#training">04 TRAINING</a><a href="#audio">05 AUDIO</a><a href="#data">06 DATA</a><a href="#account">07 ACCOUNT</a></aside>
   <main className="sv-config-main">
    <section id="identity" className="sv-config-section"><SectionHead n="01" icon={<UserIcon/>} title="System Identity" copy="The information that represents you inside STRYVEN."/><div className="sv-config-panel"><label>USERNAME<input value={state.username} maxLength={20} onChange={e=>updateProfile({username:e.target.value})} onBlur={()=>toast({title:'Identity saved',type:'success'})}/></label><div><span className="sv-config-label">NAME SIGNAL</span><div className="sv-swatch-row">{NAME_COLORS.map(color=><button type="button" key={color} aria-label={`Name color ${color}`} className={state.nameColor===color?'selected':''} style={{background:color}} onClick={()=>updateProfile({nameColor:color})}/>)}</div></div><div><span className="sv-config-label">IDENTITY FRAME</span><div className="sv-swatch-row">{BANNER_COLORS.map(color=><button type="button" key={color} aria-label={`Identity frame ${color}`} className={state.bannerColor===color?'selected':''} style={{background:color}} onClick={()=>updateProfile({bannerColor:color})}/>)}</div></div></div></section>
    <section id="interface" className="sv-config-section"><SectionHead n="02" icon={<SlidersHorizontal/>} title="Interface" copy="Control how STRYVEN behaves and how much visual motion it uses."/><div className="sv-control-list"><Toggle label="Reduced motion" description="Remove non-essential movement and transitions." value={reducedMotion} onChange={setMotion}/><Toggle label="Compact density" description="Tighter spacing for smaller screens and faster scanning." value={compact} onChange={setDensity}/><div className="sv-readonly"><span><Moon/>Visual system</span><b>OBSIDIAN / VOID BLUE</b></div><div className="sv-readonly"><span><Eye/>Current rank</span><b style={{color:rank.color}}>{rank.name}</b></div></div></section>
    <section id="environment" className="sv-config-section sv-config-section--wide"><SectionHead n="03" icon={<Palette/>} title="Environment" copy="Choose exactly what appears behind the interface. Changes apply immediately."/><div className="sv-env-tabs">{([{id:'default',label:'VOID',icon:Moon},{id:'image',label:'IMAGE',icon:ImageIcon},{id:'video',label:'VIDEO',icon:Video},{id:'animated',label:'PRESETS',icon:Sparkles}] as {id:BgType;label:string;icon:typeof Moon}[]).map(o=>{const Icon=o.icon;return <button type="button" key={o.id} className={state.backgroundType===o.id?'active':''} onClick={()=>selectBgType(o.id)}><Icon/><span>{o.label}</span></button>})}</div><div className="sv-env-actions"><div className="sv-upload-action"><div><b>Custom image</b><small>JPG / PNG / WebP / GIF · 10MB</small></div><button type="button" disabled={uploading} onClick={()=>imageRef.current?.click()}><Upload/>{uploading?'UPLOADING':'CHOOSE IMAGE'}</button><input ref={imageRef} hidden type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>handleUpload(e,'image')}/></div><div className="sv-upload-action"><div><b>Custom video</b><small>MP4 / WebM / OGG · 50MB</small></div><button type="button" disabled={uploading} onClick={()=>videoRef.current?.click()}><Upload/>{uploading?'UPLOADING':'CHOOSE VIDEO'}</button><input ref={videoRef} hidden type="file" accept="video/mp4,video/webm,video/ogg" onChange={e=>handleUpload(e,'video')}/></div><button type="button" className="sv-clear-env" onClick={clearEnvironment}><Trash2/> RESET ENVIRONMENT</button></div><div className="sv-preset-heading"><span>PRESET ENVIRONMENTS</span><small>SELECT ONE TO APPLY</small></div><div className="sv-env-grid">{BACKGROUNDS.map(bg=>{const selected=state.selectedBackgroundId===bg.id;return <button type="button" key={bg.id} className={selected?'active':''} onClick={()=>selectPreset(bg.id)} style={{background:bg.css}}><span>{bg.name}</span>{selected&&<Check/>}</button>})}</div><div className="sv-slider-grid"><Range label="BRIGHTNESS" value={state.backgroundBrightness} min={20} max={150} suffix="%" onChange={setBackgroundBrightness}/><Range label="BLUR" value={state.backgroundBlur} min={0} max={20} suffix="px" onChange={setBackgroundBlur}/><Range label="DARK OVERLAY" value={state.backgroundDarken} min={0} max={90} suffix="%" onChange={setBackgroundDarken}/></div></section>
    <section id="training" className="sv-config-section"><SectionHead n="04" icon={<Shield/>} title="Training Protocol" copy="Training remains connected to the same progression Core."/><div className="sv-control-list"><div className="sv-readonly"><span><Shield/>Training system</span><b className="good">ACTIVE</b></div><div className="sv-readonly"><span><Check/>XP rewards</span><b className="good">CONNECTED</b></div><div className="sv-readonly"><span><SettingsIcon/>Training interface</span><b>STRYVEN CORE</b></div></div></section>
    <section id="audio" className="sv-config-section"><SectionHead n="05" icon={state.soundEnabled?<Volume2/>:<VolumeX/>} title="Sound System" copy="Control system feedback and progression sounds."/><button type="button" className="sv-master-toggle" onClick={toggleSound}><span>{state.soundEnabled?<Volume2/>:<VolumeX/>}<div><b>System sounds</b><small>{state.soundEnabled?'Feedback is enabled.':'All system sounds are muted.'}</small></div></span><strong className={state.soundEnabled?'on':''}>{state.soundEnabled?'ON':'OFF'}</strong></button></section>
    <section id="data" className="sv-config-section"><SectionHead n="06" icon={<Cloud/>} title="Data & Storage" copy="Manage synchronization without touching your progression manually."/><div className="sv-data-actions"><button type="button" onClick={()=>{syncLeaderboard();toast({title:'Cloud sync requested',type:'success'})}}><Cloud/> SYNC CLOUD</button><button type="button" className="danger" onClick={()=>setResetOpen(true)}><RotateCcw/> RESET PROGRESS</button></div></section>
    <section id="account" className="sv-config-section sv-config-section--danger"><SectionHead n="07" icon={<LogOut/>} title="Account Control" copy="Your account session and cloud identity."/><div className="sv-account-row"><div><b>{user?.email||'LOCAL SESSION'}</b><small>Progression is associated with this session.</small></div><button type="button" className="danger" onClick={()=>setLogoutOpen(true)}><LogOut/> SIGN OUT</button></div></section>
   </main>
  </div>
  <ConfirmModal open={resetOpen} onClose={()=>setResetOpen(false)} onConfirm={()=>{resetAll();setResetOpen(false);toast({title:'All data reset',type:'success'})}} title="Reset All Data" message="This permanently erases your progress and history. This cannot be undone." confirmLabel="Reset Everything" danger/>
  <ConfirmModal open={logoutOpen} onClose={()=>setLogoutOpen(false)} onConfirm={signOutNow} title="Sign Out" message="Your progress is saved to the cloud." confirmLabel="Sign Out"/>
 </div>;
}
function SectionHead({n,icon,title,copy}:{n:string;icon:React.ReactNode;title:string;copy:string}){return <div className="sv-section-head-v3"><div className="sv-section-number">{n}</div><div className="sv-section-icon">{icon}</div><div><span>STRYVEN CONFIGURATION</span><h2>{title}</h2><p>{copy}</p></div></div>}
function Toggle({label,description,value,onChange}:{label:string;description:string;value:boolean;onChange:(v:boolean)=>void}){return <button type="button" className="sv-master-toggle" onClick={()=>onChange(!value)}><span><SlidersHorizontal/><div><b>{label}</b><small>{description}</small></div></span><strong className={value?'on':''}>{value?'ON':'OFF'}</strong></button>}
function Range({label,value,min,max,suffix,onChange}:{label:string;value:number;min:number;max:number;suffix:string;onChange:(v:number)=>void}){return <label className="sv-range"><span>{label}<b>{value}{suffix}</b></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
