import { useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Coins, Crown, Lock, Map, Mountain, Skull, Sparkles, Swords, Target, Trophy, Volume2, VolumeX, Zap } from 'lucide-react';
import { useStore } from '../store/useStore';
import { ALL_CHAPTERS } from '../data/story';
import type { StoryChapter, StoryMission } from '../data/story/types';
import { isMusicEnabled, setMusicEnabled } from '../lib/audioEngine';
import { toast } from '../components/ui/Toast';
import { triggerConfetti } from '../components/ui/Confetti';

type Screen = 'world' | 'chapter' | 'boss' | 'reward';
const chapters = [...ALL_CHAPTERS].sort((a, b) => a.number - b.number).slice(0, 30);
const nodes: [number, number][] = [[7,82],[11,72],[17,76],[22,65],[28,69],[33,58],[39,63],[44,51],[50,55],[55,44],[61,48],[66,37],[72,42],[77,31],[83,35],[88,25],[81,18],[73,22],[66,15],[58,20],[52,12],[45,19],[38,13],[31,20],[24,14],[18,24],[23,34],[31,39],[40,34],[49,28]];
const regions = [
  { name: 'ASHEN GATE', x: 14, y: 88, path: 'M2 94 Q8 62 28 63 Q40 66 38 92 Z' },
  { name: 'VEILWOOD', x: 43, y: 73, path: 'M28 93 Q30 52 50 48 Q67 51 67 78 Q60 94 28 93 Z' },
  { name: 'IRON WASTES', x: 79, y: 59, path: 'M57 75 Q62 37 83 31 Q98 36 98 67 Q88 82 57 75 Z' },
  { name: 'DUSK VALLEY', x: 48, y: 29, path: 'M31 47 Q37 7 59 7 Q74 12 69 43 Q53 54 31 47 Z' },
  { name: 'CROWN OF SHADOWS', x: 19, y: 31, path: 'M3 47 Q5 10 28 8 Q42 16 42 42 Q26 55 3 47 Z' }
];
const routeD = `M ${nodes.map(([x, y]) => `${x} ${y}`).join(' L ')}`;
const dateKey = (t: number) => new Date(t).toISOString().slice(0, 10);

function progress(state: ReturnType<typeof useStore>['state'], m: StoryMission) {
  switch (m.type) {
    case 'tasks': return Math.min(m.target, Object.values(state.coreCompleted).filter(Boolean).length + Object.values(state.customCompleted).filter(Boolean).length);
    case 'workout': { const today = dateKey(Date.now()); const sessions = state.workoutSessions.filter(s => dateKey(s.completedAt) === today).length; const history = state.history.some(d => d.date === today && d.workoutCompleted); return Math.min(m.target, Math.max(state.workoutsCompletedToday, sessions, history ? 1 : 0)); }
    case 'pray': return state.coreCompleted.pray ? 1 : 0;
    case 'water': return state.coreCompleted.water ? 1 : 0;
    case 'sleep': return state.coreCompleted.sleep ? 1 : 0;
    case 'read_quran': return state.coreCompleted.read_quran ? 1 : 0;
    case 'read_book': return state.coreCompleted.read ? 1 : 0;
    case 'streak': return Math.min(m.target, state.streak);
    case 'dungeon': return Math.min(m.target, state.dungeonsCleared);
    case 'discipline_score': { const enabled = state.mainTasks.filter(t => t.enabled); const done = enabled.filter(t => state.coreCompleted[t.id]).length; return enabled.length ? Math.round(done / enabled.length * 100) : 0; }
    default: return 0;
  }
}

export default function StoryModeSimple() {
  const { state, completeStoryMission, defeatStoryBoss, advanceStoryChapter, unlockLore, unlockStoryAchievement } = useStore();
  const [screen, setScreen] = useState<Screen>('world');
  const [selected, setSelected] = useState<StoryChapter>(chapters[0]);
  const [bossPhase, setBossPhase] = useState(0);
  const [reward, setReward] = useState<{ xp: number; coins: number; title?: string; lore?: string } | null>(null);
  const [music, setMusic] = useState(isMusicEnabled());
  const current = Math.min(state.storyChapter + 1, 30);
  const rows = useMemo(() => selected.missions.map(m => ({ m, p: progress(state, m), done: Boolean(state.storyCompletedMissions[m.id]) })), [selected, state]);
  const done = rows.filter(x => x.done).length;
  const open = (c: StoryChapter) => { if (c.number > current) return; setSelected(c); setScreen('chapter'); };
  const complete = (m: StoryMission) => { if (state.storyCompletedMissions[m.id]) return; const p = progress(state, m); if (p < m.target) { toast({ title: 'Mission not complete', message: `Do the objective first: ${m.title}`, type: 'info', icon: '◈' }); return; } completeStoryMission(m.id, { xp: m.xpReward, coins: m.coinReward }); toast({ title: 'Mission complete', message: `+${m.xpReward} XP · +${m.coinReward} coins`, type: 'success', icon: '✓' }); };
  const hitBoss = () => { if (bossPhase < 2) { setBossPhase(v => v + 1); return; } const b = selected.boss; defeatStoryBoss(b.id); if (b.rewardTitle) unlockStoryAchievement(b.rewardTitle); if (b.rewardLore) unlockLore(b.rewardLore); completeStoryMission(`boss_${b.id}`, { xp: b.xpReward, coins: b.coinReward }); setReward({ xp: b.xpReward, coins: b.coinReward, title: b.rewardTitle, lore: b.rewardLore }); triggerConfetti(30); setScreen('reward'); };
  const claim = () => { setReward(null); if (selected.number === current && selected.number < 30) advanceStoryChapter(); setScreen('world'); };
  if (screen === 'reward' && reward) return <div className="relative min-h-[78vh] overflow-hidden rounded-[2rem] border border-white/10 bg-[#050607] p-6 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(255,255,255,.1),transparent_45%)]"/><div className="relative mx-auto flex min-h-[68vh] max-w-xl flex-col items-center justify-center text-center"><Trophy size={42}/><div className="mt-5 text-xs font-black uppercase tracking-[.35em] text-white/40">TERRITORY CONQUERED</div><h1 className="mt-3 text-4xl font-black">{selected.title}</h1><div className="my-7 flex gap-3"><span className="rounded-xl bg-white/10 px-4 py-3 font-black"><Zap size={15} className="mr-2 inline"/>+{reward.xp} XP</span><span className="rounded-xl bg-white/10 px-4 py-3 font-black"><Coins size={15} className="mr-2 inline"/>+{reward.coins}</span></div>{reward.title&&<div className="mb-6 rounded-xl border border-white/10 bg-white/5 px-5 py-3"><b>{reward.title}</b><span className="ml-2 text-xs text-white/40">Achievement unlocked</span></div>}<button onClick={claim} className="rounded-xl bg-white px-7 py-3 font-black text-black">Return to World <ChevronRight size={17} className="ml-1 inline"/></button></div></div>;
  if (screen === 'boss') return <div className="min-h-[78vh] rounded-[2rem] border border-white/10 bg-[#050607] p-5 text-white"><button onClick={() => setScreen('chapter')} className="mb-6 flex items-center gap-2 text-xs font-bold text-white/45"><ArrowLeft size={15}/> World</button><div className="mx-auto max-w-2xl rounded-[2rem] border border-white/10 bg-black/50 p-7 text-center"><Skull className="mx-auto" size={42}/><div className="mt-4 text-xs font-black uppercase tracking-[.35em] text-white/35">BOSS CITADEL · PHASE {bossPhase + 1}/3</div><h1 className="mt-3 text-4xl font-black">{selected.boss.name}</h1><p className="mt-2 text-sm text-white/40">{['Hold your ground.','Break the pattern.','Finish the fight.'][bossPhase]}</p><div className="my-7 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-white transition-all" style={{ width: `${100 - bossPhase * 33.33}%` }}/></div><button onClick={hitBoss} className="w-full rounded-xl bg-white py-4 font-black text-black">{bossPhase === 2 ? 'DEFEAT BOSS' : 'COMPLETE PHASE'} <ChevronRight size={17} className="ml-1 inline"/></button></div></div>;
  if (screen === 'chapter') return <div className="min-h-[78vh] text-white"><div className="mb-4 flex items-center justify-between"><button onClick={() => setScreen('world')} className="flex items-center gap-2 text-xs font-bold text-white/45"><ArrowLeft size={15}/> World Map</button><button onClick={() => { const n = !music; setMusic(n); setMusicEnabled(n); }} className="rounded-xl border border-white/10 bg-white/5 p-2">{music ? <Volume2 size={16}/> : <VolumeX size={16}/>}</button></div><div className="mb-4 rounded-[2rem] border border-white/10 bg-black/40 p-6"><div className="text-xs font-black uppercase tracking-[.3em] text-white/35">{selected.region.name} · CHAPTER {String(selected.number).padStart(2, '0')}</div><div className="mt-2 flex items-end justify-between gap-4"><div><h1 className="text-3xl font-black sm:text-4xl">{selected.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/45">{selected.description}</p></div><div className="text-2xl font-black">{Math.round(done / Math.max(1, rows.length) * 100)}%</div></div><div className="mt-5 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-white" style={{ width: `${done / Math.max(1, rows.length) * 100}%` }}/></div></div><div className="rounded-[2rem] border border-white/10 bg-black/40 p-4 sm:p-6"><div className="mb-4 flex items-center justify-between"><b className="text-lg">Objectives</b><span className="text-xs text-white/40">{done}/{rows.length}</span></div><div className="space-y-2">{rows.map(({ m, p, done: d }) => <button key={m.id} onClick={() => complete(m)} className={`flex w-full items-center gap-3 rounded-xl border p-4 text-left ${d ? 'border-white/15 bg-white/10 opacity-60' : 'border-white/10 bg-white/[.03]'}`}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-white/5">{d ? <Check size={15}/> : <Target size={15}/>}</span><span className="min-w-0 flex-1"><b className="block">{m.title}</b><small className="mt-1 block text-xs text-white/35">{m.description}</small></span><span className="text-xs font-black text-white/45">{d ? 'DONE' : `${p}/${m.target}`}</span></button>)}</div>{done === rows.length ? <button onClick={() => { setBossPhase(0); setScreen('boss'); }} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-white py-4 font-black text-black"><Swords size={17}/> ENTER BOSS CITADEL</button> : <div className="mt-4 text-xs text-white/30">Complete every objective to reveal the Boss Citadel.</div>}</div></div>;
  return <WorldMap current={current} completed={state.storyChapter} open={open}/>;
}

function WorldMap({ current, completed, open }: { current: number; completed: number; open: (c: StoryChapter) => void }) {
  const [arc, setArc] = useState<'I' | 'II'>('I');
  const routeProgress = Math.max(0, Math.min(100, (Math.max(1, completed) - 1) / 29 * 100));
  return <div className="relative min-h-[86vh] overflow-hidden rounded-[2rem] border border-amber-500/20 bg-[#070807] text-white shadow-2xl">
    <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_50%_45%,rgba(91,75,40,.18),transparent_58%)]"/>
    <div className="absolute inset-0 opacity-[.12]" style={{ backgroundImage: 'linear-gradient(rgba(255,255,255,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.05) 1px,transparent 1px)', backgroundSize: '52px 52px' }}/>
    <header className="relative z-20 flex flex-wrap items-start justify-between gap-4 border-b border-white/10 bg-black/25 p-5 backdrop-blur-sm sm:p-7"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.45em] text-amber-200/45"><Map size={14}/> SYROX WORLD MAP</div><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-6xl">The Shattered Realm</h1><p className="mt-2 max-w-xl text-sm text-white/40">Follow the road from Chapter 01 to Chapter 30. Every step opens the next piece of the realm.</p></div><div className="flex gap-2"><button onClick={() => setArc('I')} className={`rounded-xl border px-3 py-2 text-[10px] font-black ${arc === 'I' ? 'border-amber-300/50 bg-amber-100 text-black' : 'border-white/10 bg-white/5 text-white/40'}`}>ARC I · ORIGIN</button><button onClick={() => setArc('II')} className={`rounded-xl border px-3 py-2 text-[10px] font-black ${arc === 'II' ? 'border-amber-300/50 bg-amber-100 text-black' : 'border-white/10 bg-white/5 text-white/40'}`}>ARC II · THE BEYOND</button></div></header>
    {arc === 'I' ? <div className="relative mx-3 mb-5 mt-3 overflow-hidden rounded-[1.75rem] border border-amber-500/15 bg-[#0b0d0b] sm:mx-7">
      <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 h-full min-h-[680px] w-full">
        <defs><filter id="routeGlow"><feGaussianBlur stdDeviation="1.4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><linearGradient id="route" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stopColor="rgba(190,140,65,.95)"/><stop offset="1" stopColor="rgba(245,220,150,.95)"/></linearGradient></defs>
        <path d="M0 94 Q15 57 35 66 T68 38 T100 9" fill="none" stroke="rgba(255,255,255,.055)" strokeWidth="7"/>
        <path d="M4 13 Q25 27 39 18 T76 18 T98 36" fill="none" stroke="rgba(255,255,255,.035)" strokeWidth="6"/>
        {regions.map((r, i) => <path key={r.name} d={r.path} fill={i % 2 ? 'rgba(70,78,60,.14)' : 'rgba(91,70,42,.14)'} stroke="rgba(214,176,101,.16)" strokeWidth=".45"/>)}
        <path d={routeD} fill="none" stroke="rgba(0,0,0,.82)" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round"/>
        <path d={routeD} fill="none" stroke="rgba(226,177,86,.78)" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="2.2 1.1"/>
        <path d={routeD} fill="none" stroke="url(#route)" strokeWidth="1.35" strokeLinecap="round" strokeLinejoin="round" strokeDasharray={`${routeProgress} ${100 - routeProgress}`} pathLength="100" filter="url(#routeGlow)"/>
        {nodes.map(([x, y], i) => <circle key={i} cx={x} cy={y} r="2.35" fill={i + 1 <= completed ? 'rgba(245,215,145,.95)' : 'rgba(255,255,255,.12)'} stroke="rgba(0,0,0,.85)" strokeWidth=".75"/>)}
        <g fill="none" stroke="rgba(255,255,255,.13)" strokeWidth=".7"><path d="M8 60 l5 -12 5 12 M13 48 l3 -7 3 7"/><path d="M83 72 l6 -15 6 15 M88 57 l4 -10 4 10"/><path d="M47 88 l6 -14 6 14 M52 74 l4 -9 4 9"/></g>
      </svg>
      <div className="relative min-h-[680px]">
        {regions.map((r, i) => <div key={r.name} className="pointer-events-none absolute z-[1] -translate-x-1/2 -translate-y-1/2 text-center" style={{ left: `${r.x}%`, top: `${r.y}%` }}><div className="text-[9px] font-black uppercase tracking-[.4em] text-amber-100/30">{r.name}</div><div className="mt-1 text-[7px] uppercase tracking-[.28em] text-white/10">TERRITORY {i + 1}</div></div>)}
        {chapters.map((c, i) => { const [x, y] = nodes[i] ?? [50, 50]; const unlocked = c.number <= current; const done = c.number <= completed; const isCurrent = c.number === current; return <button key={c.id} disabled={!unlocked} onClick={() => open(c)} style={{ left: `${x}%`, top: `${y}%` }} className={`group absolute z-10 -translate-x-1/2 -translate-y-1/2 ${unlocked ? 'cursor-pointer' : 'cursor-not-allowed'}`}>{isCurrent && <span className="absolute -inset-3 animate-pulse rounded-full border border-amber-300/30"/>}<span className={`relative flex h-12 w-12 items-center justify-center rounded-full border-2 shadow-[0_0_25px_rgba(0,0,0,.8)] transition duration-300 group-hover:scale-125 sm:h-14 sm:w-14 ${done ? 'border-amber-200 bg-amber-100 text-black' : isCurrent ? 'border-amber-300 bg-[#16120b] text-amber-200' : unlocked ? 'border-amber-200/45 bg-[#0b0d0b] text-white' : 'border-white/10 bg-[#080908] text-white/20'}`}>{done ? <Check size={17}/> : unlocked ? <Crown size={17}/> : <Lock size={15}/>}</span><span className={`mt-2 block whitespace-nowrap text-[8px] font-black uppercase tracking-[.22em] ${done ? 'text-amber-100/80' : unlocked ? 'text-white/65' : 'text-white/20'}`}>CH {String(c.number).padStart(2, '0')}</span>{unlocked && <span className="pointer-events-none absolute bottom-full left-1/2 mb-3 hidden w-48 -translate-x-1/2 rounded-xl border border-amber-200/15 bg-black/95 p-3 text-center shadow-xl group-hover:block"><b className="block text-[11px]">{c.title}</b><span className="mt-1 block text-[9px] text-amber-100/35">{c.region.name} · {c.boss.name}</span></span>}</button>; })}
        <div className="absolute left-[6%] bottom-[5%] z-[2] hidden rounded-xl border border-white/10 bg-black/55 px-3 py-2 backdrop-blur-sm sm:block"><div className="flex items-center gap-2 text-[8px] font-black uppercase tracking-[.25em] text-white/30"><Mountain size={13}/> THE ROAD OF DISCIPLINE</div><div className="mt-1 text-[9px] text-white/20">Follow the illuminated route.</div></div>
        <div className="absolute right-[5%] top-[7%] z-[2] rounded-xl border border-amber-200/10 bg-black/55 px-3 py-2 backdrop-blur-sm"><div className="flex items-center gap-2 text-[8px] font-black uppercase tracking-[.25em] text-amber-100/35"><Skull size={12}/> BOSS CITADELS</div><div className="mt-1 text-[9px] text-white/20">Every territory ends in a trial.</div></div>
      </div>
    </div> : <div className="relative mx-3 mb-5 mt-3 flex min-h-[680px] items-center justify-center overflow-hidden rounded-[1.75rem] border border-amber-500/15 bg-[radial-gradient(circle_at_50%_40%,rgba(104,77,38,.2),transparent_45%)] sm:mx-7"><div className="absolute inset-0 opacity-20"><div className="absolute left-[15%] top-[20%] h-44 w-44 rounded-full border border-amber-200/10"/><div className="absolute right-[14%] bottom-[18%] h-56 w-56 rounded-full border border-amber-200/10"/><Mountain className="absolute left-[18%] bottom-[18%] text-white/10" size={160}/><Mountain className="absolute right-[14%] top-[17%] text-white/10" size={190}/></div><div className="relative z-10 max-w-lg p-7 text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full border border-amber-200/15 bg-white/5"><Sparkles size={30} className="text-amber-100/35"/></div><div className="mt-6 text-[10px] font-black uppercase tracking-[.45em] text-amber-100/30">ARC II · THE BEYOND</div><h2 className="mt-3 text-4xl font-black sm:text-5xl">Beyond the Shattered Realm</h2><p className="mt-4 text-sm leading-7 text-white/35">The next continent will continue directly from Chapter 30 with new territories, routes, bosses and lore.</p><div className="mt-6 inline-flex items-center gap-2 rounded-xl border border-amber-200/10 bg-white/5 px-5 py-3 text-[10px] font-black tracking-[.25em] text-white/35"><Lock size={13}/> ARC II · LOCKED</div></div></div>}
    <footer className="relative z-20 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 bg-black/25 px-5 py-4 text-[9px] font-black uppercase tracking-[.25em] text-white/30 sm:px-7"><span><span className="mr-2 inline-block h-2 w-2 rounded-full bg-amber-200"/> {completed}/30 chapters conquered</span><span>Current Chapter {current}/30</span><span className="flex items-center gap-2"><Skull size={12}/> Complete the route to reach each Boss Citadel</span></footer>
  </div>;
}
