import { useMemo, useState } from 'react';
import { Brain, Sparkles, WandSparkles } from 'lucide-react';

type Goal = 'strength' | 'vertical' | 'conditioning' | 'balanced';
type Level = 'beginner' | 'intermediate' | 'advanced';
const goalNames: Record<Goal,string> = { strength:'Strength & Muscle', vertical:'Vertical Jump', conditioning:'Conditioning', balanced:'Balanced Discipline' };
const pools: Record<Goal,string[]> = {
  strength:['Push-ups','Pike Push-ups','Diamond Push-ups','Bodyweight Squats','Reverse Lunges','Glute Bridges','Back Widows'],
  vertical:['Pogo Jumps','Squat Jumps','Broad Jumps','Split Jumps','Calf Raises','Tuck Jumps','Depth Drop to Jump'],
  conditioning:['Burpees','Mountain Climbers','High Knees','Skater Hops','Bear Crawls','Shadow Boxing','Jumping Jacks'],
  balanced:['Push-ups','Bodyweight Squats','Reverse Lunges','Pike Push-ups','Pogo Jumps','Mountain Climbers','Plank'],
};
export function AIWorkoutBuilder() {
  const [goal,setGoal]=useState<Goal>('balanced'); const [level,setLevel]=useState<Level>('intermediate'); const [minutes,setMinutes]=useState(45); const [equipment,setEquipment]=useState('none'); const [result,setResult]=useState<string[]>([]);
  const build=()=>{ const count=level==='advanced'?6:level==='beginner'?4:5; const pool=[...pools[goal]].sort(()=>Math.random()-.5).slice(0,count); const sets=level==='advanced'?4:3; const generated=['Dynamic Stretching — 5 min',...pool.map((x,i)=>`${x} — ${sets} sets × ${i%2?'8-12':'10-15'}`),'Plyometric Finisher — 3 rounds']; setResult(generated); localStorage.setItem('stryven-ai-last-plan',JSON.stringify({goal,level,minutes,equipment,generated,createdAt:Date.now()})); };
  const summary=useMemo(()=>`${goalNames[goal]} • ${level} • ${minutes} min • ${equipment==='none'?'No equipment':equipment}`,[goal,level,minutes,equipment]);
  return <div className="space-y-5"><div className="card p-5 sm:p-7 relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-violet-500/10 via-transparent to-ember-500/10 pointer-events-none"/><div className="relative"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-xl theme-accent-bg flex items-center justify-center"><Brain size={24}/></div><div><p className="text-xs uppercase tracking-[.25em] theme-accent">Shadow AI</p><h1 className="font-display text-2xl sm:text-3xl font-black">AI Workout Builder</h1></div></div><p className="text-sm text-ink-300 mt-3 max-w-2xl">Tell Shadow your goal, level and available time. It builds a practical workout with stretching, main work and a plyometric finisher.</p></div></div>
  <div className="card p-5 grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-xs text-ink-400">Goal</span><select className="input w-full" value={goal} onChange={e=>setGoal(e.target.value as Goal)}>{Object.entries(goalNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="space-y-2"><span className="text-xs text-ink-400">Level</span><select className="input w-full" value={level} onChange={e=>setLevel(e.target.value as Level)}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label className="space-y-2"><span className="text-xs text-ink-400">Time: {minutes} min</span><input className="w-full" type="range" min="20" max="90" step="5" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label className="space-y-2"><span className="text-xs text-ink-400">Equipment</span><select className="input w-full" value={equipment} onChange={e=>setEquipment(e.target.value)}><option value="none">None</option><option value="basic">Basic equipment</option><option value="gym">Full gym</option></select></label><button onClick={build} className="btn-primary md:col-span-2 py-3"><WandSparkles size={18}/> Build My Workout</button></div>
  <div className="card p-5"><div className="flex items-center justify-between gap-3 mb-4"><div><h2 className="font-display text-xl font-bold">{result.length?'Generated Plan':'Ready to Forge'}</h2><p className="text-xs text-ink-400 mt-1">{summary}</p></div>{result.length>0&&<Sparkles className="theme-accent" size={20}/>}</div>{result.length===0?<p className="text-sm text-ink-400 py-5 text-center">Shadow will generate a plan from your answers.</p>:<div className="space-y-2">{result.map((x,i)=><div key={i} className="p-3 rounded-xl bg-ink-950/40 border border-white/5 flex gap-3"><span className="theme-accent font-mono text-xs pt-0.5">{String(i+1).padStart(2,'0')}</span><span>{x}</span></div>)}<p className="text-xs text-ink-400 pt-2">Plan saved locally. Open Workout to customize your six days.</p></div>}</div></div>;
}
export default AIWorkoutBuilder;
