import { useMemo, useState } from 'react';
import { ArrowRight, Bot, Check, ChevronRight, Dumbbell, RefreshCw, Send, ShieldCheck, Sparkles, Target, Trophy, X } from 'lucide-react';
import { buildShadowPlan, explainExercise, findSwap, type ShadowDifficulty, type ShadowEquipment, type ShadowExercise, type ShadowGoal } from '../lib/shadowWorkoutEngine';

type Message={role:'user'|'assistant';text:string};

function parseRequest(text:string){
  const t=text.toLowerCase();
  const goal:ShadowGoal=t.includes('قوة')||t.includes('strength')?'strength':t.includes('مرونة')||t.includes('mobility')?'mobility':t.includes('قفز')||t.includes('سلة')||t.includes('basket')||t.includes('vertical')||t.includes('sports')?'sports':'fitness';
  const equipment:ShadowEquipment=t.includes('جيم')||t.includes('gym')?'gym':t.includes('أدوات')||t.includes('home')||t.includes('بيت')?'home':'bodyweight';
  const daysMatch=t.match(/([1-6])\s*(?:أيام|ايام|days|day)/); const days=daysMatch?Number(daysMatch[1]):6;
  const minMatch=t.match(/([2-9][0-9])\s*(?:دقيقة|دقايق|minutes|min)/); const minutes=minMatch?Number(minMatch[1]):50;
  const difficulty:ShadowDifficulty=t.includes('متقدم')||t.includes('advanced')?'advanced':t.includes('مبتد')||t.includes('beginner')?'beginner':'intermediate';
  return {goal,equipment,days:Math.min(6,Math.max(1,days)),minutes:Math.min(75,Math.max(25,minutes)),difficulty};
}

export function ShadowAIV2(){
 const [input,setInput]=useState('');
 const [config,setConfig]=useState(parseRequest(''));
 const [messages,setMessages]=useState<Message[]>([{role:'assistant',text:'أنا Shadow. قولي هدفك، كام يوم، مدة التمرين، والمعدات اللي عندك. مثال: «عايز برنامج قوة 6 أيام من غير أدوات، 50 دقيقة».'}]);
 const [plan,setPlan]=useState(()=>buildShadowPlan(config));
 const [week,setWeek]=useState(0); const [day,setDay]=useState(0); const [selected,setSelected]=useState<ShadowExercise|null>(null); const [completed,setCompleted]=useState<Record<string,boolean>>({});
 const current=plan.weeks[week]?.[day];
 const completion=current?Math.round(current.exercises.filter((x,i)=>completed[`${week}-${day}-${x.id}-${i}`]).length/current.exercises.length*100):0;
 const send=()=>{const text=input.trim();if(!text)return;const next=parseRequest(text);setConfig(next);const nextPlan=buildShadowPlan(next);setPlan(nextPlan);setWeek(0);setDay(0);setInput('');setMessages(m=>[...m,{role:'user',text},{role:'assistant',text:`تمام. بنيت لك ${next.days} أيام × ${nextPlan.weeks.length} أسبوع، بمدة ${next.minutes} دقيقة. التوزيع متحقق منه بحيث كل تمرين له movement group واضح، والـplyometrics لا تدخل عشوائيًا في أيام الجزء العلوي.`}]);};
 const regenerate=()=>{const next=buildShadowPlan({...config,weeks:12});setPlan(next);setMessages(m=>[...m,{role:'assistant',text:'أعدت توزيع البرنامج مع الحفاظ على نفس الهدف والمستوى والمعدات.'}]);};
 const swap=(x:ShadowExercise)=>{const replacement=findSwap(x,config.equipment,config.goal,config.difficulty,[x.id]);if(!replacement){setMessages(m=>[...m,{role:'assistant',text:'مش لاقي بديل بنفس الـmovement pattern والمعدات من غير ما أضعف اليوم. الأفضل نخلي التمرين الحالي.'}]);return;}setPlan(p=>{const copy=p.weeks.map(w=>w.map(d=>({...d,exercises:d.exercises.map(e=>e.id===x.id?replacement:e)})));return {...p,weeks:copy};});setSelected(null);setMessages(m=>[...m,{role:'assistant',text:`بدلت ${x.name} بـ ${replacement.name} مع الحفاظ على نفس المجموعة والـmovement pattern.`}]);};
 const summary=useMemo(()=>plan.validation,[plan]);
 return <section className="space-y-5 pb-10">
  <div className="relative overflow-hidden rounded-3xl border border-ember-500/20 bg-gradient-to-br from-ember-500/10 via-black/40 to-transparent p-5 sm:p-7"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-ember-500/10 blur-3xl"/><div className="relative flex items-start gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl border border-ember-500/30 bg-ember-500/10"><Bot size={28} className="text-ember-400"/></div><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.22em] text-ember-400"><Sparkles size={14}/> Shadow AI</div><h1 className="mt-1 text-2xl font-black sm:text-3xl">Your adaptive workout coach.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Talk normally. Shadow turns your request into a complete multi-day program, validates the split, and lets you swap exercises without breaking the plan.</p></div></div></div>
  <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_300px]">
   <div className="rounded-2xl border border-white/10 bg-black/30 p-4 sm:p-5"><div className="mb-4 flex items-center gap-2"><Bot size={18} className="text-ember-400"/><b>Chat with Shadow</b></div><div className="min-h-[230px] max-h-[360px] space-y-3 overflow-y-auto pr-1">{messages.map((m,i)=><div key={i} className={`flex ${m.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[88%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.role==='user'?'bg-ember-500 text-white':'border border-white/10 bg-white/[.04] text-slate-300'}`}>{m.text}</div></div>)}</div><div className="mt-4 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="مثال: عايز قوة 6 أيام من غير أدوات..." className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/40 px-4 py-3 text-sm text-white outline-none focus:border-ember-500/50"/><button onClick={send} className="flex shrink-0 items-center gap-2 rounded-xl bg-ember-500 px-4 py-3 text-sm font-black text-white"><Send size={16}/><span className="hidden sm:inline">Send</span></button></div></div>
   <aside className="rounded-2xl border border-white/10 bg-black/30 p-4"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-slate-500"><Target size={15}/> Current build</div><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span className="text-slate-500">Goal</span><b className="capitalize">{config.goal}</b></div><div className="flex justify-between"><span className="text-slate-500">Days</span><b>{config.days}</b></div><div className="flex justify-between"><span className="text-slate-500">Session</span><b>{config.minutes}m</b></div><div className="flex justify-between"><span className="text-slate-500">Equipment</span><b className="capitalize">{config.equipment}</b></div><div className="flex justify-between"><span className="text-slate-500">Level</span><b className="capitalize">{config.difficulty}</b></div></div><button onClick={regenerate} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-bold text-slate-200"><RefreshCw size={16}/> Regenerate</button></aside>
  </div>
  <div className="rounded-2xl border border-white/10 bg-black/30 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Dumbbell size={18} className="text-ember-400"/><h2 className="text-xl font-black">12-Week Program</h2></div><p className="mt-1 text-xs text-slate-500">{summary.valid?'Validation passed':'Validation needs review'} · {summary.warnings.length} coaching warnings</p></div><button onClick={()=>{localStorage.setItem('forged-shadow-ai-workout-plan',JSON.stringify(plan));setMessages(m=>[...m,{role:'assistant',text:'البرنامج الكامل اتجهز للنقل إلى Workout. استخدم Apply في شاشة الـWorkout.'}]);}} className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-ember-500 to-orange-600 px-4 py-3 text-sm font-black text-white"><ArrowRight size={16}/> Apply Full Plan</button></div>
   <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{plan.weeks.map((_,i)=><button key={i} onClick={()=>{setWeek(i);setDay(0)}} className={`shrink-0 rounded-xl border px-4 py-2 text-xs font-black ${week===i?'border-ember-500/50 bg-ember-500/10 text-ember-300':'border-white/5 text-slate-500'}`}>W{i+1}</button>)}</div>
   <div className="mt-3 flex gap-2 overflow-x-auto pb-1">{plan.weeks[week]?.map((d,i)=><button key={d.day} onClick={()=>setDay(i)} className={`shrink-0 rounded-xl border px-4 py-3 text-left ${day===i?'border-ember-500/50 bg-ember-500/10':'border-white/5 bg-white/[.02]'}`}><div className="text-[10px] uppercase text-slate-500">Day {d.day}</div><div className="mt-1 text-xs font-bold">{d.title}</div></button>)}</div>
   {current&&<div className="mt-4 rounded-2xl border border-white/10 bg-white/[.02] p-4"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-black">{current.title}</h3><p className="text-xs text-slate-500">{current.exercises.length} exercises · {current.estimatedMinutes} min</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs font-bold">{completion}%</span></div><div className="space-y-2">{current.exercises.map((x,i)=>{const key=`${week}-${day}-${x.id}-${i}`;return <div key={`${x.id}-${i}`} className="flex items-center gap-3 rounded-xl border border-white/5 p-3"><button onClick={()=>setCompleted(v=>({...v,[key]:!v[key]}))} className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border ${completed[key]?'border-emerald-400/40 bg-emerald-400/10 text-emerald-300':'border-white/10 text-slate-500'}`}>{completed[key]?<Check size={16}/>:i+1}</button><button onClick={()=>setSelected(x)} className="min-w-0 flex-1 text-left"><b className={completed[key]?'text-slate-500 line-through':'text-slate-100'}>{x.name}</b><span className="mt-0.5 block text-xs text-slate-500">{x.target} · {x.reps} · {x.slot} · {x.rest}s</span></button><ChevronRight size={15} className="text-slate-600"/></div>})}</div></div>}
  </div>
  <div className="grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-black/30 p-4"><ShieldCheck className="text-emerald-400" size={19}/><b className="mt-2 block">Split validation</b><p className="mt-1 text-xs text-slate-500">Duplicate IDs and incompatible exercise placement are checked before delivery.</p></div><div className="rounded-2xl border border-white/10 bg-black/30 p-4"><Trophy className="text-amber-400" size={19}/><b className="mt-2 block">Progression</b><p className="mt-1 text-xs text-slate-500">12 weeks are generated with phase-based recovery and workload scaling.</p></div><div className="rounded-2xl border border-white/10 bg-black/30 p-4"><Sparkles className="text-ember-400" size={19}/><b className="mt-2 block">Smart swaps</b><p className="mt-1 text-xs text-slate-500">Swap an exercise while preserving its movement pattern and training role.</p></div></div>
  {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4" onClick={()=>setSelected(null)}><div className="w-full max-w-lg rounded-2xl border border-white/10 bg-ink-950 p-5" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><span className="rounded-full border border-ember-500/30 bg-ember-500/10 px-2 py-1 text-[10px] font-bold uppercase text-ember-300">{selected.group}</span><h2 className="mt-2 text-xl font-black">{selected.name}</h2><p className="mt-1 text-xs text-slate-500">{selected.target} · {selected.pattern}</p></div><button onClick={()=>setSelected(null)}><X size={18}/></button></div><p className="mt-5 rounded-xl border border-white/5 bg-white/[.03] p-4 text-sm leading-6 text-slate-300">{explainExercise(selected)}</p><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>swap(selected)} className="rounded-xl bg-ember-500 px-4 py-3 text-sm font-black text-white">Swap Exercise</button><button onClick={()=>setSelected(null)} className="rounded-xl border border-white/10 px-4 py-3 text-sm font-bold">Keep</button></div></div></div>}
 </section>;
}
