import { useMemo, useState } from 'react';
import { Brain, Check, ChevronRight, Dumbbell, Flame, Play, RotateCcw, Sparkles, Target, Timer, Trophy } from 'lucide-react';

type Group='push'|'pull'|'legs'|'core'|'plyometric'|'mobility'|'conditioning';
type Equipment='bodyweight'|'home'|'gym';
type Goal='strength'|'fitness'|'mobility'|'sports';
type Difficulty='beginner'|'intermediate'|'advanced';
type Exercise={name:string;group:Group;target:string;equipment:Equipment[];reps:string;rest:number;slot:'warmup'|'main'|'accessory'|'finisher';cue:string};

const DB:Exercise[]=[
{name:'Arm Circles',group:'mobility',target:'Shoulders',equipment:['bodyweight','home','gym'],reps:'30s',rest:20,slot:'warmup',cue:'Smooth controlled circles.'},
{name:'World’s Greatest Stretch',group:'mobility',target:'Hips + T-spine',equipment:['bodyweight','home','gym'],reps:'4/side',rest:20,slot:'warmup',cue:'Never force the range.'},
{name:'Ankle Rocks',group:'mobility',target:'Ankles',equipment:['bodyweight','home','gym'],reps:'10/side',rest:20,slot:'warmup',cue:'Keep heel grounded.'},
{name:'Push-up',group:'push',target:'Chest + triceps',equipment:['bodyweight','home','gym'],reps:'6–15',rest:75,slot:'main',cue:'Brace your core and keep one line.'},
{name:'Pike Push-up',group:'push',target:'Shoulders + triceps',equipment:['bodyweight','home','gym'],reps:'5–12',rest:90,slot:'main',cue:'Lower under control.'},
{name:'Close-grip Push-up',group:'push',target:'Triceps + chest',equipment:['bodyweight','home','gym'],reps:'6–12',rest:75,slot:'accessory',cue:'Keep elbows controlled.'},
{name:'Backpack Floor Press',group:'push',target:'Chest + triceps',equipment:['home'],reps:'8–15',rest:90,slot:'main',cue:'Use only a secure load.'},
{name:'Backpack Row',group:'pull',target:'Back + biceps',equipment:['home'],reps:'8–15',rest:75,slot:'main',cue:'Pull toward the ribs.'},
{name:'Band Row',group:'pull',target:'Upper back',equipment:['home'],reps:'10–15',rest:75,slot:'main',cue:'Do not swing.'},
{name:'Assisted Pull-up',group:'pull',target:'Lats + arms',equipment:['gym'],reps:'5–10',rest:105,slot:'main',cue:'Lower slowly.'},
{name:'Lat Pulldown',group:'pull',target:'Lats',equipment:['gym'],reps:'8–12',rest:90,slot:'main',cue:'Pull to upper chest.'},
{name:'Bodyweight Squat',group:'legs',target:'Quads + glutes',equipment:['bodyweight','home','gym'],reps:'8–20',rest:75,slot:'main',cue:'Knees track naturally.'},
{name:'Reverse Lunge',group:'legs',target:'Quads + glutes',equipment:['bodyweight','home','gym'],reps:'6–12/side',rest:75,slot:'main',cue:'Stay balanced.'},
{name:'Split Squat',group:'legs',target:'Quads + glutes',equipment:['bodyweight','home','gym'],reps:'6–12/side',rest:90,slot:'main',cue:'Use support if needed.'},
{name:'Glute Bridge',group:'legs',target:'Glutes + hips',equipment:['bodyweight','home','gym'],reps:'10–20',rest:60,slot:'accessory',cue:'Pause at the top.'},
{name:'Calf Raise',group:'legs',target:'Calves',equipment:['bodyweight','home','gym'],reps:'10–20',rest:50,slot:'accessory',cue:'Use a steady tempo.'},
{name:'Dead Bug',group:'core',target:'Core control',equipment:['bodyweight','home','gym'],reps:'6–12/side',rest:50,slot:'accessory',cue:'Keep the lower back controlled.'},
{name:'Front Plank',group:'core',target:'Core',equipment:['bodyweight','home','gym'],reps:'20–60s',rest:50,slot:'accessory',cue:'Breathe normally.'},
{name:'Side Plank',group:'core',target:'Lateral stability',equipment:['bodyweight','home','gym'],reps:'15–45s/side',rest:50,slot:'accessory',cue:'Stack the hips.'},
{name:'Pogo Hops',group:'plyometric',target:'Elasticity + landing',equipment:['bodyweight','home','gym'],reps:'3×10–20s',rest:75,slot:'finisher',cue:'Quiet landings.'},
{name:'Snap-down',group:'plyometric',target:'Landing mechanics',equipment:['bodyweight','home','gym'],reps:'3×4–6',rest:75,slot:'main',cue:'Own every landing.'},
{name:'Squat Jump',group:'plyometric',target:'Vertical power',equipment:['bodyweight','home','gym'],reps:'3×4–8',rest:105,slot:'main',cue:'Quality over height.'},
{name:'Lateral Bound',group:'plyometric',target:'Lateral power',equipment:['bodyweight','home','gym'],reps:'3×4–8/side',rest:105,slot:'main',cue:'Stabilize each landing.'},
{name:'Mountain Climber',group:'conditioning',target:'Conditioning + core',equipment:['bodyweight','home','gym'],reps:'20–45s',rest:50,slot:'finisher',cue:'Choose a sustainable pace.'},
{name:'Jumping Jack',group:'conditioning',target:'Conditioning',equipment:['bodyweight','home','gym'],reps:'30–60s',rest:45,slot:'finisher',cue:'Step instead of jump if needed.'},
];

const by=(g:Group,e:Equipment)=>DB.filter(x=>x.group===g&&x.equipment.includes(e));
const uniquePick=(groups:Group[],equipment:Equipment,count:number,seed:number)=>{const used=new Set<string>();const out:Exercise[]=[];for(let i=0;i<count;i++){const pool=groups.flatMap(g=>by(g,equipment)).filter(x=>!used.has(x.name));if(!pool.length)break;const item=pool[(seed+i*3)%pool.length];used.add(item.name);out.push(item);}return out;};
const slots=(goal:Goal,day:number):Group[]=>goal==='mobility'?['mobility','core']:goal==='sports'?day%3===0?['legs','plyometric','core']:day%3===1?['push','core']:['pull','conditioning']:day%2===0?['pull','legs','core']:['push','pull','core'];

export function ShadowAIComplete(){
 const [goal,setGoal]=useState<Goal>('strength');const [difficulty,setDifficulty]=useState<Difficulty>('intermediate');const [equipment,setEquipment]=useState<Equipment>('bodyweight');const [days,setDays]=useState(6);const [minutes,setMinutes]=useState(50);const [week,setWeek]=useState(1);const [activeDay,setActiveDay]=useState(0);const [done,setDone]=useState<Record<string,boolean>>({});const [active,setActive]=useState<Exercise|null>(null);const [seconds,setSeconds]=useState(0);const [running,setRunning]=useState(false);
 const plan=useMemo(()=>Array.from({length:days},(_,i)=>{const groups=slots(goal,i);const names=days===6?['Push + Plyometric','Pull + Plyometric','Legs + Plyometric','Upper + Core','Lower + Power','Conditioning + Mobility']:Array.from({length:days},(_,n)=>`Day ${n+1}`);const warm=uniquePick(['mobility'],equipment,1,i+week);const main=uniquePick(groups.filter(g=>g!=='core'),equipment,Math.max(2,minutes<40?2:3),i+week+2);const core=uniquePick(['core'],equipment,1,i+week+5);const fin=goal==='sports'||goal==='fitness'?uniquePick(['conditioning','plyometric'].filter(g=>groups.includes(g as Group)) as Group[],equipment,1,i+week+7):[];return{day:i+1,title:names[i]||`Day ${i+1}`,items:[...warm,...main,...core,...fin]};}),[days,equipment,goal,minutes,week]);
 const current=plan[activeDay];const total=current?.items.length||0;const completed=current?.items.filter((x)=>done[`${current.day}:${x.name}`]).length||0;const sets=difficulty==='beginner'?2:difficulty==='intermediate'?3:4;
 const toggle=(x:Exercise)=>setDone(v=>({...v,[`${current.day}:${x.name}`]:!v[`${current.day}:${x.name}`]}));
 return <section className="space-y-5 pb-10"><div className="relative overflow-hidden rounded-3xl border border-white/10 bg-black/40 p-5 sm:p-7"><div className="absolute -right-20 -top-20 h-52 w-52 rounded-full bg-ember-500/10 blur-3xl"/><div className="relative flex items-start gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl border border-ember-500/30 bg-ember-500/10"><Brain className="text-ember-400" size={28}/></div><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.22em] text-ember-400"><Sparkles size={14}/> Shadow Core</div><h1 className="mt-1 text-2xl font-black sm:text-3xl">Your adaptive training system.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Exercises are assigned by movement group, target and equipment. Shadow prevents duplicate exercises inside the same session and keeps plyometrics in power-focused positions.</p></div></div></div>
 <div className="grid gap-4 lg:grid-cols-[280px_1fr]"><aside className="rounded-2xl border border-white/10 bg-black/30 p-4 space-y-4"><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">Goal</p><div className="grid grid-cols-2 gap-2">{(['strength','fitness','mobility','sports'] as Goal[]).map(x=><button key={x} onClick={()=>setGoal(x)} className={`rounded-xl px-3 py-2 text-xs font-bold capitalize ${goal===x?'bg-ember-500/15 text-ember-300 border border-ember-500/40':'border border-white/5 text-slate-400'}`}>{x}</button>)}</div></div><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">Difficulty</p><div className="grid grid-cols-3 gap-2">{(['beginner','intermediate','advanced'] as Difficulty[]).map(x=><button key={x} onClick={()=>setDifficulty(x)} className={`rounded-xl px-2 py-2 text-[11px] font-bold capitalize ${difficulty===x?'bg-white/10 text-white':'bg-black/20 text-slate-500'}`}>{x}</button>)}</div></div><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">Equipment</p><select value={equipment} onChange={e=>setEquipment(e.target.value as Equipment)} className="w-full rounded-xl border border-white/10 bg-black/40 px-3 py-2 text-sm text-slate-200"><option value="bodyweight">Bodyweight</option><option value="home">Home</option><option value="gym">Gym</option></select></div><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">Days / Week</p><div className="grid grid-cols-3 gap-2">{[3,4,5,6].map(x=><button key={x} onClick={()=>setDays(x)} className={`rounded-xl py-2 text-sm font-bold ${days===x?'bg-ember-500 text-white':'bg-white/5 text-slate-400'}`}>{x}</button>)}</div></div><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">Session</p><input type="range" min="25" max="75" step="5" value={minutes} onChange={e=>setMinutes(+e.target.value)} className="w-full"/><div className="flex justify-between text-xs text-slate-500"><span>25m</span><span>{minutes}m</span><span>75m</span></div></div><button onClick={()=>{setDone({});setWeek(w=>w+1)}} className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-ember-500 to-orange-600 px-4 py-3 text-sm font-black text-white"><Sparkles size={16}/> Regenerate Week</button></aside>
 <div className="space-y-4"><div className="flex gap-2 overflow-x-auto pb-1">{plan.map((d,i)=><button key={d.day} onClick={()=>setActiveDay(i)} className={`min-w-[125px] rounded-2xl border p-3 text-left ${activeDay===i?'border-ember-500/50 bg-ember-500/10':'border-white/5 bg-black/20'}`}><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Day {d.day}</div><div className="mt-1 text-xs font-bold text-white">{d.title}</div><div className="mt-2 text-[10px] text-slate-500">{d.items.length} exercises</div></button>)}</div><div className="rounded-2xl border border-white/10 bg-black/30 p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-ember-400">Today’s objective</p><h2 className="mt-1 text-xl font-black">{current?.title}</h2></div><div className="text-right"><div className="text-lg font-black">{completed}/{total}</div><div className="text-[10px] uppercase text-slate-500">complete</div></div></div><div className="space-y-2">{current?.items.map((x,i)=><div key={x.name} className="flex items-center gap-3 rounded-xl border border-white/5 bg-white/[.02] p-3"><button onClick={()=>toggle(x)} className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border ${done[`${current.day}:${x.name}`]?'border-emerald-400/40 bg-emerald-400/10 text-emerald-300':'border-white/10 text-slate-500'}`}>{done[`${current.day}:${x.name}`]?<Check size={17}/>:<span className="text-xs">{i+1}</span>}</button><button onClick={()=>setActive(x)} className="min-w-0 flex-1 text-left"><div className={`font-bold ${done[`${current.day}:${x.name}`]?'text-slate-500 line-through':'text-slate-100'}`}>{x.name}</div><div className="mt-0.5 text-xs text-slate-500">{x.target} · {x.reps} · {x.slot}</div></button><ChevronRight size={16} className="text-slate-600"/></div>)}</div></div></div></div>
 <div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-black/30 p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase text-slate-500"><Target size={15}/> Split integrity</div><div className="mt-2 text-2xl font-black">100%</div><p className="mt-1 text-xs text-slate-500">Every exercise has one primary movement group.</p></div><div className="rounded-2xl border border-white/10 bg-black/30 p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase text-slate-500"><Flame size={15}/> Week</div><div className="mt-2 text-2xl font-black">{week}</div><p className="mt-1 text-xs text-slate-500">Progression phase advances when you regenerate.</p></div><div className="rounded-2xl border border-white/10 bg-black/30 p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase text-slate-500"><Trophy size={15}/> Sets</div><div className="mt-2 text-2xl font-black">{sets}</div><p className="mt-1 text-xs text-slate-500">Working sets per main movement.</p></div></div>
 <div className="flex flex-wrap gap-2">{['No duplicate exercises','Equipment filtered','Plyometric placement','Target-specific selection'].map(x=><span key={x} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5 text-[11px] font-bold text-slate-400">✓ {x}</span>)}</div>
 {active&&<div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" onClick={()=>setActive(null)}><div className="w-full max-w-md rounded-3xl border border-white/10 bg-[#101114] p-5" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><div><div className="text-xs font-bold uppercase tracking-wider text-ember-400">{active.slot}</div><h3 className="mt-1 text-xl font-black">{active.name}</h3></div><button onClick={()=>setActive(null)} className="rounded-xl bg-white/5 p-2 text-slate-400">×</button></div><div className="mt-5 grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-white/5 p-3"><span className="text-xs text-slate-500">Target</span><div className="font-bold">{active.target}</div></div><div className="rounded-xl bg-white/5 p-3"><span className="text-xs text-slate-500">Reps</span><div className="font-bold">{active.reps}</div></div><div className="rounded-xl bg-white/5 p-3"><span className="text-xs text-slate-500">Rest</span><div className="font-bold">{active.rest}s</div></div><div className="rounded-xl bg-white/5 p-3"><span className="text-xs text-slate-500">Group</span><div className="font-bold capitalize">{active.group}</div></div></div><p className="mt-4 text-sm leading-6 text-slate-400">{active.cue}</p><div className="mt-4 flex gap-2"><button onClick={()=>setRunning(v=>!v)} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-ember-500 py-3 text-sm font-black text-white"><Play size={16}/>{running?'Pause':'Start'}</button><button onClick={()=>setSeconds(0)} className="rounded-xl bg-white/5 px-4 text-slate-300"><RotateCcw size={16}/></button><button onClick={()=>setSeconds(s=>s+active.rest)} className="rounded-xl bg-white/5 px-4 text-slate-300"><Timer size={16}/></button></div><div className="mt-3 text-center text-2xl font-black">{seconds}s</div></div></div>}
 </section>;
}
