import { lazy, Suspense, useEffect, useState } from 'react';
import { Navigation, type ViewId } from './components/Navigation';
import { Background } from './components/Background';
import { ToastContainer } from './components/ui/Toast';
import { Confetti } from './components/ui/Confetti';
import { ErrorBoundary } from './components/ui/ErrorBoundary';
import { AuthProvider, useAuth } from './lib/auth';
import { useStore } from './store/useStore';
import { syncSoundFlag } from './lib/sound';
import { ensureStoryReset } from './lib/story/storyReset';
import { usePWA } from './hooks/usePWA';
import { InstallButton } from './components/pwa/InstallButton';
import { StoryProgressBridge } from './components/StoryProgressBridge';
import { Loader2 } from 'lucide-react';
import './theme.css';
import './theme-overrides.css';
import './theme-identities.css';
import './theme-motion.css';
import './stryven-ui-system.css';
import './stryven-redesign.css';
import './stryven-shell.css';
import './stryven-pages.css';
import './stryven-settings.css';
import './stryven-dungeons.css';
import './story-map-responsive.css';
import './stryven-character.css';
import './stryven-ui-polish.css';
import './stryven-performance.css';
import './scroll-fix.css';

const Dashboard = lazy(() => import('./views/Dashboard').then((m) => ({ default: m.Dashboard })));
const Tasks = lazy(() => import('./views/Tasks').then((m) => ({ default: m.Tasks })));
const StoryMode = lazy(() => import('./views/StoryModeSimpleV2'));
const WorkoutWithAIPlan = lazy(() => import('./components/WorkoutWithAIPlan').then((m) => ({ default: m.WorkoutWithAIPlan })));
const Dungeons = lazy(() => import('./views/Dungeons').then((m) => ({ default: m.Dungeons })));
const Profile = lazy(() => import('./views/Profile').then((m) => ({ default: m.Profile })));