import { useId, useMemo, useState } from 'react';

interface DataPoint { date: string; score: number; isToday: boolean; }
interface DisciplineLineChartProps { data: DataPoint[]; height?: number; showToday?: boolean; animate?: boolean; }

export function DisciplineLineChart({ data, height = 270, showToday = true, animate = true }: DisciplineLineChartProps) {
  const [hovered, setHovered] = useState<number | null>(null);
  const rawId = useId(); const id = rawId.replace(/:/g, '');
  const W = 920, H = 320; const pad = { top: 46, right: 30, bottom: 48, left: 30 }; const iw = W-pad.left-pad.right; const ih = H-pad.top-pad.bottom;
  const points = useMemo(() => { if (!data.length) return []; const step = data.length > 1 ? iw/(data.length-1) : 0; return data.map((d,i)=>({...d,x:pad.left+i*step,y:pad.top+ih-(Math.max(0,Math.min(100,d.score))/100)*ih})); }, [data,iw,ih]);
  const stats = useMemo(() => { const ti=data.findIndex(p=>p.isToday); const i=ti>=0?ti:Math.max(0,data.length-1); const week=data.slice(Math.max(0,i-6),i+1); const avg=week.length?Math.round(week.reduce((s,p)=>s+p.score,0)/week.length):0; const best=data.length?Math.max(...data.map(p=>p.score)):0; const delta=week.length>1?week[week.length-1].score-week[0].score:0; return {today:data[i]?.score??0,avg,best,delta,todayIndex:ti}; },[data]);
  const line=points.map((p,i)=>`${i?'L':'M'}${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' '); const area=points.length?`${line} L${points.at(-1)!.x} ${pad.top+ih} L${points[0].x} ${pad.top+ih} Z`:'';
  const formatDate=(d:string)=>new Date(`${d}T00:00:00`).toLocaleDateString('en',{month:'short',day:'numeric'}); const hover=hovered===null?null:points[hovered];
  return <div className="w-full">
    <div className="mb-4 flex items-center justify-between gap-4"><div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300 shadow-[0_0_10px_rgba(103,232,249,.8)]"/><p className="text-[9px] font-bold uppercase tracking-[0.28em] text-slate-500">Performance Index</p></div><p className="mt-1.5 text-lg font-black tracking-tight text-slate-100">Discipline Matrix</p></div><div className="flex items-center gap-4"><div className="hidden text-right sm:block"><p className="text-[8px] uppercase tracking-[0.2em] text-slate-600">7D AVG</p><p className="text-sm font-bold tabular-nums text-slate-300">{stats.avg}%</p></div><div className="h-9 w-px bg-white/[0.07]"/><div className="text-right"><p className="text-[8px] uppercase tracking-[0.2em] text-slate-600">TODAY</p><p className="text-2xl font-black leading-none tabular-nums text-cyan-300">{stats.today}%</p></div></div></div>
    <div className="relative overflow-hidden rounded-[22px] border border-white/[0.08] bg-gradient-to-br from-[#0b1118] via-[#080c12] to-[#0a0b10] shadow-[0_18px_50px_rgba(0,0,0,.28),inset_0_1px_0_rgba(255,255,255,.035)]"><div className="pointer-events-none absolute -right-24 -top-24 h-56 w-56 rounded-full bg-cyan-400/[0.045] blur-3xl"/><div className="pointer-events-none absolute -bottom-28 left-1/3 h-52 w-52 rounded-full bg-violet-500/[0.035] blur-3xl"/><div className="relative px-3 pt-3 sm:px-5 sm:pt-4"><div className="flex items-center justify-between text-[8px] font-semibold uppercase tracking-[0.18em] text-slate-600"><span>30 DAY WINDOW</span><span>100% MAX</span></div></div>
      {points.length===0?<div className="flex items-center justify-center py-20 text-sm text-slate-500">No discipline history yet.</div>:<div className="relative"><svg viewBox={`0 0 ${W} ${H}`} width="100%" height={height} preserveAspectRatio="none" className="block w-full select-none" role="img" aria-label={`Discipline Matrix. Today ${stats.today} percent. Seven day average ${stats.avg} percent. Best ${stats.best} percent.`}><defs><linearGradient id={`${id}-area`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#22d3ee" stopOpacity=".18"/><stop offset=".45" stopColor="#8b5cf6" stopOpacity=".075"/><stop offset="1" stopColor="#8b5cf6" stopOpacity="0"/></linearGradient><linearGradient id={`${id}-line`} x1="0" y1="0" x2="1" y2="0"><stop offset="0" stopColor="#67e8f9"/><stop offset=".5" stopColor="#a78bfa"/><stop offset="1" stopColor="#f0abfc"/></linearGradient><filter id={`${id}-glow`} x="-10%" y="-50%" width="120%" height="200%"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
        {[0,25,50,75,100].map(v=>{const y=pad.top+ih-v/100*ih;return <line key={v} x1={pad.left} x2={W-pad.right} y1={y} y2={y} stroke="rgba(148,163,184,.075)" strokeWidth="1" strokeDasharray={v===0?undefined:'1 10'}/>})}
        {points.length>1&&<path d={area} fill={`url(#${id}-area)`}/>} {points.length>1&&<path d={line} fill="none" stroke={`url(#${id}-line)`} strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round" filter={`url(#${id}-glow)`} className={animate?'chart-line-draw':''}/>} 
        {stats.todayIndex>=0&&showToday&&<g><line x1={points[stats.todayIndex].x} x2={points[stats.todayIndex].x} y1={pad.top-6} y2={pad.top+ih} stroke="#67e8f9" strokeOpacity=".18" strokeWidth="1" strokeDasharray="2 7"/><circle cx={points[stats.todayIndex].x} cy={points[stats.todayIndex].y} r="15" fill="#67e8f9" fillOpacity=".055"/><circle cx={points[stats.todayIndex].x} cy={points[stats.todayIndex].y} r="6" fill="#d5fbff" stroke="#071016" strokeWidth="2.5"/><g transform={`translate(${Math.max(8,Math.min(W-104,points[stats.todayIndex].x-52))},${Math.max(7,points[stats.todayIndex].y-52)})`}><rect width="104" height="27" rx="8" fill="#0d151d" stroke="rgba(103,232,249,.28)"/><text x="52" y="17.5" textAnchor="middle" fontSize="9" fontWeight="800" fill="#a5f3fc" letterSpacing=".5">TODAY · {stats.today}%</text></g></g>}
        {points.map((p,i)=><g key={p.date} onMouseEnter={()=>setHovered(i)} onMouseLeave={()=>setHovered(null)}><rect x={Math.max(pad.left,p.x-18)} y={pad.top} width="36" height={ih} fill="transparent" className="cursor-crosshair"/>{hovered===i&&i!==stats.todayIndex&&<g><line x1={p.x} x2={p.x} y1={pad.top} y2={pad.top+ih} stroke="rgba(255,255,255,.12)" strokeDasharray="3 5"/><circle cx={p.x} cy={p.y} r="5" fill="#f0abfc" stroke="#080c12" strokeWidth="2"/></g>}</g>)}
        {points.map((p,i)=>(i%7===0||i===points.length-1)?<text key={`d-${p.date}`} x={p.x} y={H-12} textAnchor="middle" fontSize="9" fill="rgba(148,163,184,.36)">{formatDate(p.date)}</text>:null)}</svg>{hover&&<div className="pointer-events-none absolute top-3 -translate-x-1/2 rounded-xl border border-white/[0.09] bg-[#10151d]/95 px-3 py-2 shadow-2xl backdrop-blur-md" style={{left:`${(hover.x/W)*100}%`}}><p className="text-[9px] font-semibold uppercase tracking-wider text-slate-500">{formatDate(hover.date)}</p><p className="mt-0.5 text-sm font-black tabular-nums text-fuchsia-200">{hover.score}%</p></div>}</div>}
      <div className="flex items-center justify-between border-t border-white/[0.055] px-4 py-2.5 text-[8px] font-semibold uppercase tracking-[0.16em] text-slate-600 sm:px-5"><span>Daily discipline</span><span className={stats.delta>0?'text-emerald-400':stats.delta<0?'text-rose-400':'text-slate-500'}>{stats.delta>0?`▲ ${stats.delta}%`:stats.delta<0?`▼ ${Math.abs(stats.delta)}%`:'— Stable'} 7D movement</span></div></div>
  </div>;
}

export function buildDisciplineData(history: { date: string; disciplineScore: number }[], days = 30): DataPoint[] { const today=new Date(); const todayStr=today.toISOString().slice(0,10); const byDate=new Map(history.map(h=>[h.date,h.disciplineScore])); return Array.from({length:days},(_,n)=>{const d=new Date(today);d.setDate(d.getDate()-(days-1-n));const date=d.toISOString().slice(0,10);return {date,score:Math.max(0,Math.min(100,byDate.get(date)??0)),isToday:date===todayStr};}); }
