import { useId, useMemo, useState } from 'react';

interface DataPoint { date: string; score: number; isToday: boolean; }
interface DisciplineLineChartProps { data: DataPoint[]; height?: number; showToday?: boolean; animate?: boolean; }

export function DisciplineLineChart({ data, height = 270, showToday = true, animate = true }: DisciplineLineChartProps) {
  const [hovered, setHovered] = useState<number | null>(null);
  const id = useId().replace(/:/g, '');
  const W = 920, H = 320, pad = { top: 42, right: 30, bottom: 48, left: 30 }, iw = W - pad.left - pad.right, ih = H - pad.top - pad.bottom;
  const points = useMemo(() => data.map((d,i)=>({...d,x:pad.left+(data.length>1?i*iw/(data.length-1):iw/2),y:pad.top+ih-(Math.max(0,Math.min(100,d.score))/100)*ih})),[data,iw,ih]);
  const todayIndex=points.findIndex(p=>p.isToday); const stats=useMemo(()=>{const ti=data.findIndex(p=>p.isToday),i=ti>=0?ti:Math.max(0,data.length-1),week=data.slice(Math.max(0,i-6),i+1),avg=week.length?Math.round(week.reduce((s,p)=>s+p.score,0)/week.length):0,best=data.length?Math.max(...data.map(p=>p.score)):0;return{today:data[i]?.score??0,avg,best,todayIndex:ti};},[data]);
  const line=points.map((p,i)=>`${i?'L':'M'}${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' '); const area=points.length?`${line} L${points.at(-1)!.x} ${pad.top+ih} L${points[0].x} ${pad.top+ih} Z`:''; const formatDate=(d:string)=>new Date(`${d}T00:00:00`).toLocaleDateString('en',{month:'short',day:'numeric'}); const hover=hovered===null?null:points[hovered];
  return <div className="w-full">
    <div className="mb-4 flex items-center justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[0.28em] text-slate-600">DISCIPLINE / 30 DAYS</p><p className="mt-1 text-lg font-black tracking-tight text-slate-100">Performance trajectory</p></div><div className="flex items-center gap-4"><div className="hidden text-right sm:block"><p className="text-[8px] uppercase tracking-[0.2em] text-slate-600">7D AVG</p><p className="text-sm font-bold tabular-nums text-slate-300">{stats.avg}%</p></div><div className="h-9 w-px bg-white/[0.07]"/><div className="text-right"><p className="text-[8px] uppercase tracking-[0.2em] text-slate-600">TODAY</p><p className="text-2xl font-black leading-none tabular-nums text-cyan-300">{stats.today}%</p></div></div></div>
    <div className="relative overflow-hidden rounded-[22px] border border-white/[0.08] bg-[#090d13] shadow-[0_18px_50px_rgba(0,0,0,.28),inset_0_1px_0_rgba(255,255,255,.035)]">
      {points.length===0?<div className="flex items-center justify-center py-20 text-sm text-slate-500">No discipline history yet.</div>:<div className="relative"><svg viewBox={`0 0 ${W} ${H}`} width="100%" height={height} preserveAspectRatio="none" className="block w-full select-none" role="img" aria-label={`Discipline performance. Today ${stats.today} percent. Seven day average ${stats.avg} percent. Best ${stats.best} percent.`}><defs><linearGradient id={`${id}a`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#38bdf8" stopOpacity=".20"/><stop offset=".48" stopColor="#6366f1" stopOpacity=".07"/><stop offset="1" stopColor="#6366f1" stopOpacity="0"/></linearGradient><linearGradient id={`${id}l`} x1="0" y1="0" x2="1" y2="0"><stop offset="0" stopColor="#38bdf8"/><stop offset=".5" stopColor="#818cf8"/><stop offset="1" stopColor="#c084fc"/></linearGradient><filter id={`${id}g`} x="-10%" y="-50%" width="120%" height="200%"><feGaussianBlur stdDeviation="2.8" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
        {[0,25,50,75,100].map(v=>{const y=pad.top+ih-v/100*ih;return <g key={v}><line x1={pad.left} x2={W-pad.right} y1={y} y2={y} stroke="rgba(148,163,184,.065)" strokeWidth="1" strokeDasharray={v?'2 11':undefined}/>{v>0&&<text x={W-pad.right+5} y={y+3} fontSize="9" fill="rgba(148,163,184,.22)">{v}</text>}</g>})}
        {points.length>1&&<path d={area} fill={`url(#${id}a)`}/>} {points.length>1&&<path d={line} fill="none" stroke={`url(#${id}l)`} strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round" filter={`url(#${id}g)`} className={animate?'chart-line-draw':''}/>} 
        {todayIndex>=0&&showToday&&<g><line x1={points[todayIndex].x} x2={points[todayIndex].x} y1={pad.top-5} y2={pad.top+ih} stroke="#38bdf8" strokeOpacity=".2" strokeWidth="1" strokeDasharray="3 8"/><circle cx={points[todayIndex].x} cy={points[todayIndex].y} r="15" fill="#38bdf8" fillOpacity=".055"/><circle cx={points[todayIndex].x} cy={points[todayIndex].y} r="6" fill="#e0f2fe" stroke="#071017" strokeWidth="2.5"/><g transform={`translate(${Math.max(8,Math.min(W-104,points[todayIndex].x-52))},${Math.max(7,points[todayIndex].y-50)})`}><rect width="104" height="27" rx="8" fill="#0d141c" stroke="rgba(56,189,248,.3)"/><text x="52" y="17.5" textAnchor="middle" fontSize="9" fontWeight="800" fill="#7dd3fc" letterSpacing=".5">TODAY · {stats.today}%</text></g></g>}
        {points.map((p,i)=><g key={p.date} onMouseEnter={()=>setHovered(i)} onMouseLeave={()=>setHovered(null)}><rect x={Math.max(pad.left,p.x-18)} y={pad.top} width="36" height={ih} fill="transparent" className="cursor-crosshair"/>{hovered===i&&i!==todayIndex&&<g><line x1={p.x} x2={p.x} y1={pad.top} y2={pad.top+ih} stroke="rgba(255,255,255,.11)" strokeDasharray="3 6"/><circle cx={p.x} cy={p.y} r="5" fill="#c084fc" stroke="#080c12" strokeWidth="2"/></g>}</g>)}
        {points.map((p,i)=>(i%7===0||i===points.length-1)?<text key={`d-${p.date}`} x={p.x} y={H-12} textAnchor="middle" fontSize="9" fill="rgba(148,163,184,.34)">{formatDate(p.date)}</text>:null)}</svg>{hover&&<div className="pointer-events-none absolute top-3 -translate-x-1/2 rounded-xl border border-white/[0.09] bg-[#10151d]/95 px-3 py-2 shadow-2xl backdrop-blur-md" style={{left:`${(hover.x/W)*100}%`}}><p className="text-[9px] font-semibold uppercase tracking-wider text-slate-500">{formatDate(hover.date)}</p><p className="mt-0.5 text-sm font-black tabular-nums text-fuchsia-200">{hover.score}%</p></div>}</div>}
      <div className="flex items-center justify-between border-t border-white/[0.055] px-4 py-2.5 text-[8px] font-semibold uppercase tracking-[0.16em] text-slate-600"><span>Daily discipline</span><span>0 — 100%</span></div></div>
  </div>;
}

export function buildDisciplineData(history: { date: string; disciplineScore: number }[], days = 30): DataPoint[] { const today=new Date(); const todayStr=today.toISOString().slice(0,10); const byDate=new Map(history.map(h=>[h.date,h.disciplineScore])); return Array.from({length:days},(_,n)=>{const d=new Date(today);d.setDate(d.getDate()-(days-1-n));const date=d.toISOString().slice(0,10);return {date,score:Math.max(0,Math.min(100,byDate.get(date)??0)),isToday:date===todayStr};}); }
